<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Using the xtractomatic routines version 3.4 • xtractomatic</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Using the xtractomatic routines version 3.4">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">xtractomatic</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">3.4.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/Usingxtractomatic.html">Using the xtractomatic routines version 3.4</a>
    </li>
  </ul>
</li>
<li>
  <a href="../news/index.html">Changelog</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/rmendels/xtractomatic">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><script src="Usingxtractomatic_files/htmlwidgets-1.3/htmlwidgets.js"></script><script src="Usingxtractomatic_files/jquery-1.12.4/jquery.min.js"></script><link href="Usingxtractomatic_files/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet">
<script src="Usingxtractomatic_files/datatables-binding-0.5/datatables.js"></script><link href="Usingxtractomatic_files/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet">
<link href="Usingxtractomatic_files/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet">
<script src="Usingxtractomatic_files/dt-core-1.10.16/js/jquery.dataTables.min.js"></script><link href="Usingxtractomatic_files/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet">
<script src="Usingxtractomatic_files/crosstalk-1.0.0/js/crosstalk.min.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Using the xtractomatic routines version 3.4</h1>
                        <h4 class="author">Roy Mendelssohn and Cara Wilson</h4>
            
            <h4 class="date">2019-03-14</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/rmendels/xtractomatic/blob/master/vignettes/Usingxtractomatic.Rmd"><code>vignettes/Usingxtractomatic.Rmd</code></a></small>
      <div class="hidden name"><code>Usingxtractomatic.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p><code>xtractomatic</code> is an <span style="color:red">R</span> package developed to subset and extract satellite and other oceanographic related data from a remote server. The program can extract data for a moving point in time along a user-supplied set of longitude, latitude and time points; in a 3D bounding box; or within a polygon (through time). The <code>xtractomatic</code> functions were originally developed for the marine biology tagging community, to match up environmental data available from satellites (sea-surface temperature, sea-surface chlorophyll, sea-surface height, sea-surface salinity, vector winds) to track data from various tagged animals or shiptracks (<code>xtracto</code>). The package has since been extended to include the routines that extract data a 3D bounding box (<code>xtracto_3D</code>) or within a polygon (<code>xtractogon</code>). The <code>xtractomatic</code> package accesses data that are served through the <span style="color:red">ERDDAP</span> server at the NOAA/SWFSC Environmental Research Division in Santa Cruz, California. In order that the user not be overwhelmed when searching for datasets, only a selected number of the datasets on that <span style="color:red">ERDDAP</span> server, those viewed as most useful, are supported. The <span style="color:red">ERDDAP</span> server can also be directly accessed at <a href="http://coastwatch.pfeg.noaa.gov/erddap" class="uri">http://coastwatch.pfeg.noaa.gov/erddap</a>. <span style="color:red">ERDDAP</span> is a simple to use yet powerful web data service developed by Bob Simons.</p>
<p>This is the third version of <code>xtractomatic</code>. The original version was created by Dave Foley for <span style="color:red">Matlab</span> and was modified for <span style="color:red">R</span> by Cindy Bessey and Dave Foley. That version used a precurser to <span style="color:red">ERDDAP</span> called <span style="color:red">BobDAP</span>. <span style="color:red">BobDAP</span> was less flexible and provided access to fewer datasets than does <span style="color:red">ERDDAP</span>. The second version of xtractomatic was written by Roy Mendelssohn to use <span style="color:red">ERDDAP</span> rather than <span style="color:red">BobDAP</span>. This version, also written by Roy Mendelssohn, has many improvements including access to many more datasets, improved speed, better error checking, crude search capabilites, and plotting routines, and is the first version as a true <span style="color:red">R</span> package.</p>
<p>This version also includes the latest version of the <code>cmocean</code> colormaps, designed by Kristen Thyng (see <a href="http://matplotlib.org/cmocean/" class="uri">http://matplotlib.org/cmocean/</a> and <a href="https://github.com/matplotlib/cmocean" class="uri">https://github.com/matplotlib/cmocean</a>). These colormaps were initally developed for Python, and a version of the colormaps is used in the <code>oce</code> package by Dan Kelley and Clark Richards, but the colormaps used here are the version as of late 2017. The colormaps are loaded automatically as <code>colors</code>, see <code><a href="https://www.rdocumentation.org/packages/utils/topics/str">str(colors)</a></code>. Several of the examples make use of the <code>cmocean</code> colormaps.</p>
<div id="refactor" class="section level3">
<h3 class="hasAnchor">
<a href="#refactor" class="anchor"></a>IMPORTANT - If you have used xtractomatic before</h3>
<p>The code has undergone a major refactoring, in particular there is no longer separate code to handle bathymetry and other datasets without time. In order to have a cleaner design to go with these changes, the order of the arguments to the functions has changed, “tpos” no longer has to be passed for a dataset without time, and “xlen” and “ylen” have default values (see next section). Also in <code><a href="../reference/xtracto.html">xtracto()</a></code> the return now includes the parameter name, so instead of one element being just “mean” it will be “mean sst” for example. The changes in the function arguments makes them closer to that in <code>rerddapXtracto</code>, see next section.</p>
</div>
<div id="important---likely-last-version-of-xtractomatic" class="section level3">
<h3 class="hasAnchor">
<a href="#important---likely-last-version-of-xtractomatic" class="anchor"></a>IMPORTANT - Likely last version of xtractomatic</h3>
<p>This will likely be the last version of <code>xtractomatic</code>, except for bug fixes or changes needed to stay compatible with new versions of <span style="color:red">R</span>, or changes in <span style="color:red">ERDDAP</span> and the applications it uses. Development effort will be put into improving the <code>rerddapXtracto</code> package, with the intent that users will eventually migrate to <code>rerddapXtracto</code>. As mentioned above, the changes in the function arguments will help to simplify this migration.</p>
</div>
<div id="the-main-xtractomatic-functions" class="section level3">
<h3 class="hasAnchor">
<a href="#the-main-xtractomatic-functions" class="anchor"></a>The Main xtractomatic functions</h3>
<p>There are three main data extraction functions in the <code>xtractomatic</code> package:</p>
<ul>
<li><p><code>xtracto &lt;- function(dtype, xpos, ypos, tpos = NA, xlen = 0., ylen = 0., verbose=FALSE)</code></p></li>
<li><p><code>xtracto_3D &lt;- function(dtype, xpos, ypos, tpos = NA, verbose=FALSE)</code></p></li>
<li><p><code>xtractogon &lt;- function(dtype, xpos, ypos, tpos = NA,  verbose = FALSE)</code></p></li>
</ul>
<p>There are two information functions in the <code>xtractomatic</code> package:</p>
<ul>
<li><p>`searchData &lt;- function(searchList= “varname:chl”)</p></li>
<li><p><code>getInfo &lt;- function(dtype)</code></p></li>
</ul>
<p>The <code>dtype</code> parameter in the data extraction routines specifies a combination of which dataset on the <span style="color:red">ERDDAP</span> server to access, and as well as which parameter from that dataset. The first sections demonstrate how to use these functions in realistic settings. The <a href="#dataset">Selecting a dataset</a> section shows how to find the <code>dtype</code> or other parameters of interest from the available datasets.</p>
</div>
</div>
<div id="setting-up" class="section level2">
<h2 class="hasAnchor">
<a href="#setting-up" class="anchor"></a>Setting up</h2>
<p><code>xtractomatic</code> uses the <code>httr</code>, <code>ncdf4</code>, <code>readr</code> and <code>sp</code> packages, and these packages must be installed first or <code>xtractomatic</code> will fail to install.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/install.packages">install.packages</a></span>(<span class="st">"httr"</span>, <span class="dt">dependencies =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/install.packages">install.packages</a></span>(<span class="st">"ncdf4"</span>,<span class="dt">dependencies =</span> <span class="ot">TRUE</span>) </a>
<a class="sourceLine" id="cb1-3" title="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/install.packages">install.packages</a></span>(<span class="st">"readr"</span>, <span class="dt">dependencies =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb1-4" title="4"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/install.packages">install.packages</a></span>(<span class="st">"sp"</span>, <span class="dt">dependencies =</span> <span class="ot">TRUE</span>)</a></code></pre></div>
<p>The <code>xtractomatic</code> package is available from <span style="color:blue">CRAN</span> and can be installed by:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb2-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/install.packages">install.packages</a></span>(<span class="st">"xtractomatic"</span>)</a></code></pre></div>
<p>or the development version is available from [Github](<a href="https://github.com/rmendels/xtractomatic" class="uri">https://github.com/rmendels/xtractomatic</a> and can be installed from <span style="color:blue">Github</span>,</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/install.packages">install.packages</a></span>(<span class="st">"devtools"</span>)</a>
<a class="sourceLine" id="cb3-2" title="2">devtools<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/devtools/topics/reexports">install_github</a></span>(<span class="st">"rmendels/xtractomatic"</span>)</a></code></pre></div>
<p>Once installed, to use <code>xtractomatic</code> do</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"xtractomatic"</span>)</a></code></pre></div>
<p>If the other libraries (<code>httr</code>, <code>ncdf4</code>, <code>readr</code> and <code>sp</code>) have been installed they will be found and do not need to be explicitly loaded.</p>
<div id="using-the-r-code-examples" class="section level3">
<h3 class="hasAnchor">
<a href="#using-the-r-code-examples" class="anchor"></a>Using the R code examples</h3>
<p>Besides the <code>xtractomatic</code> packages, the examples below depend on <code>DT</code>, <code>ggplot2</code>, <code>lubridate</code>, <code>mapdata</code>, and <code>reshape2</code>. These can be loaded beforehand (assuming they have been installed):</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"DT"</span>)</a>
<a class="sourceLine" id="cb5-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"ggplot2"</span>)</a>
<a class="sourceLine" id="cb5-3" title="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"lubridate"</span>)</a>
<a class="sourceLine" id="cb5-4" title="4"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"mapdata"</span>)</a>
<a class="sourceLine" id="cb5-5" title="5"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(<span class="st">"reshape2"</span>)</a></code></pre></div>
<p>In order that the code snippets can be more stand-alone, the needed libraries are always <code>required</code> in the examples.</p>
<p>It should be emphasized that these other packages are used to manipulate and plot the data in <span style="color:red">R</span>, other packages could be used as well. The use of <code>xtractomatic</code> does not depend on these other packages.</p>
<p>There are also several <span style="color:red">R</span> functions defined within the document that are used in other code examples. These include <code>chlaAvg</code>, <code>upwell</code>, and <code>plotUpwell</code>.</p>
</div>
</div>
<div id="getting-started" class="section level2">
<h2 class="hasAnchor">
<a href="#getting-started" class="anchor"></a>Getting Started</h2>
<div id="an-xtracto-example" class="section level3">
<h3 class="hasAnchor">
<a href="#an-xtracto-example" class="anchor"></a>An xtracto example</h3>
<p>In this section we extract data along a trackline found in the <span style="color:red">Marlintag38606</span> dataset, which is the track of a tagged marlin in the Pacific Ocean (courtesy of Dr. Mike Musyl of the Pelagic Research Group LLC), and show some simple plots of the extracted data.</p>
<p>The <span style="color:red">Marlintag38606</span> dataset is loaded when you load the <code>xtractomatic</code> library. The structure of this dataframe is shown by:</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb6-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(Marlintag38606)</a>
<a class="sourceLine" id="cb6-3" title="3"><span class="co">#&gt; 'data.frame':    152 obs. of  7 variables:</span></a>
<a class="sourceLine" id="cb6-4" title="4"><span class="co">#&gt;  $ date  : Date, format: "2003-04-23" "2003-04-24" ...</span></a>
<a class="sourceLine" id="cb6-5" title="5"><span class="co">#&gt;  $ lon   : num  204 204 204 204 204 ...</span></a>
<a class="sourceLine" id="cb6-6" title="6"><span class="co">#&gt;  $ lat   : num  19.7 19.8 20.4 20.3 20.3 ...</span></a>
<a class="sourceLine" id="cb6-7" title="7"><span class="co">#&gt;  $ lowLon: num  204 204 204 204 204 ...</span></a>
<a class="sourceLine" id="cb6-8" title="8"><span class="co">#&gt;  $ higLon: num  204 204 204 204 204 ...</span></a>
<a class="sourceLine" id="cb6-9" title="9"><span class="co">#&gt;  $ lowLat: num  19.7 18.8 18.8 18.9 18.9 ...</span></a>
<a class="sourceLine" id="cb6-10" title="10"><span class="co">#&gt;  $ higLat: num  19.7 20.9 21.9 21.7 21.7 ...</span></a></code></pre></div>
<p>The <span style="color:red">Marlintag38606</span> dataset consists of three variables, the <span style="color:red">date</span>, <span style="color:red">longitude</span> and <span style="color:red">latitude</span> of the tagged fish, which are used as the <span style="color:red">xpos</span>, <span style="color:red">ypos</span> and <span style="color:red">tpos</span> arguments in <code>xtracto</code>. The parameters <span style="color:red">xlen</span> and <span style="color:red">ylen</span> specify the spatial “radius” (actually a box, not a circle) around the point to search in for existing data. These can also be input as a time-dependent vector of values, but here a set value of 0.2 degrees is used. The example extracts <span style="color:red">SeaWiFS chlorophyll data</span>, using a dataset that is an 8 day composite. This dataset is specified by the <span style="color:red">dtype</span> of <code>"swchla8day"</code> in the <code>xtracto</code> function. In a later section it is explained how to access different satellite datasets other than the one shown here.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb7-2" title="2"></a>
<a class="sourceLine" id="cb7-3" title="3"><span class="co"># First we will copy the Marlintag38606 data into a variable </span></a>
<a class="sourceLine" id="cb7-4" title="4"><span class="co"># called tagData  so that subsequent code will be more generic.  </span></a>
<a class="sourceLine" id="cb7-5" title="5"></a>
<a class="sourceLine" id="cb7-6" title="6">tagData &lt;-<span class="st"> </span>Marlintag38606</a>
<a class="sourceLine" id="cb7-7" title="7">xpos &lt;-<span class="st"> </span>tagData<span class="op">$</span>lon</a>
<a class="sourceLine" id="cb7-8" title="8">ypos &lt;-<span class="st"> </span>tagData<span class="op">$</span>lat</a>
<a class="sourceLine" id="cb7-9" title="9">tpos &lt;-<span class="st"> </span>tagData<span class="op">$</span>date</a>
<a class="sourceLine" id="cb7-10" title="10">swchl &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto.html">xtracto</a></span>(<span class="st">"swchla8day"</span>, xpos, ypos, <span class="dt">tpos =</span> tpos, , <span class="dt">xlen =</span> <span class="fl">.2</span>, <span class="dt">ylen =</span> <span class="fl">.2</span>)</a></code></pre></div>
<p>This command can take a while to run depending on your internet speed and how busy is the server. With a fairly decent internet connection it took ~25 seconds. The default is to run in quiet mode, if you would prefer to see output, as confirmation that the script is running, use <code>verbose=TRUE</code></p>
<p>When the extraction has completed the data frame <code>swchl</code> will contain as many columns as data points in the input file (in this case 152) and will have 11 columns:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(swchl)</a>
<a class="sourceLine" id="cb8-2" title="2"><span class="co">#&gt; 'data.frame':    152 obs. of  11 variables:</span></a>
<a class="sourceLine" id="cb8-3" title="3"><span class="co">#&gt;  $ mean chlorophyll  : num  0.073 NaN 0.074 0.0653 0.0403 ...</span></a>
<a class="sourceLine" id="cb8-4" title="4"><span class="co">#&gt;  $ stdev chlorophyll : num  NA NA 0.00709 0.00768 0.02278 ...</span></a>
<a class="sourceLine" id="cb8-5" title="5"><span class="co">#&gt;  $ n                 : int  1 0 16 4 7 9 4 3 0 6 ...</span></a>
<a class="sourceLine" id="cb8-6" title="6"><span class="co">#&gt;  $ satellite date    : chr  "2003-04-19" "2003-04-27" "2003-04-27" "2003-04-27" ...</span></a>
<a class="sourceLine" id="cb8-7" title="7"><span class="co">#&gt;  $ requested lon min : num  204 204 204 204 204 ...</span></a>
<a class="sourceLine" id="cb8-8" title="8"><span class="co">#&gt;  $ requested lon max : num  204 204 204 204 204 ...</span></a>
<a class="sourceLine" id="cb8-9" title="9"><span class="co">#&gt;  $ requested lat min : num  19.6 19.7 20.3 20.2 20.2 ...</span></a>
<a class="sourceLine" id="cb8-10" title="10"><span class="co">#&gt;  $ requested lat max : num  19.8 19.9 20.5 20.4 20.4 ...</span></a>
<a class="sourceLine" id="cb8-11" title="11"><span class="co">#&gt;  $ requested date    : num  12165 12166 12172 12173 12174 ...</span></a>
<a class="sourceLine" id="cb8-12" title="12"><span class="co">#&gt;  $ median chlorophyll: num  0.073 NA 0.073 0.0645 0.031 ...</span></a>
<a class="sourceLine" id="cb8-13" title="13"><span class="co">#&gt;  $ mad chlorophyll   : num  0 NA 0.00297 0.00741 0.0089 ...</span></a></code></pre></div>
</div>
<div id="plotting-the-results" class="section level3">
<h3 class="hasAnchor">
<a href="#plotting-the-results" class="anchor"></a>Plotting the results</h3>
<p>We plot the track line with the locations colored according to the mean of the satellite <span style="color:red">chlorophyll</span> around that point. Positions where there was a tag location but no <span style="color:red">chlorophyll</span> values are also shown.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb9-2" title="2"><span class="co">#&gt; Loading required package: ggplot2</span></a>
<a class="sourceLine" id="cb9-3" title="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(mapdata)</a>
<a class="sourceLine" id="cb9-4" title="4"><span class="co">#&gt; Loading required package: mapdata</span></a>
<a class="sourceLine" id="cb9-5" title="5"><span class="co">#&gt; Loading required package: maps</span></a>
<a class="sourceLine" id="cb9-6" title="6"><span class="co"># First combine the two dataframes (the input and the output) into one, </span></a>
<a class="sourceLine" id="cb9-7" title="7"><span class="co"># so it will be easy to take into account the locations that didn’t </span></a>
<a class="sourceLine" id="cb9-8" title="8"><span class="co"># retrieve a value.</span></a>
<a class="sourceLine" id="cb9-9" title="9"></a>
<a class="sourceLine" id="cb9-10" title="10">alldata &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cbind">cbind</a></span>(swchl, tagData)</a>
<a class="sourceLine" id="cb9-11" title="11"></a>
<a class="sourceLine" id="cb9-12" title="12"><span class="co"># adjust the longitudes to be (-180,180)</span></a>
<a class="sourceLine" id="cb9-13" title="13">alldata<span class="op">$</span>lon &lt;-<span class="st"> </span>alldata<span class="op">$</span>lon <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb9-14" title="14"><span class="co"># Create a variable that shows if chla is missing</span></a>
<a class="sourceLine" id="cb9-15" title="15">alldata<span class="op">$</span>missing &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/NA">is.na</a></span>(alldata<span class="op">$</span>mean) <span class="op">*</span><span class="st"> </span><span class="dv">1</span></a>
<a class="sourceLine" id="cb9-16" title="16"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/colnames">colnames</a></span>(alldata)[<span class="dv">1</span>] &lt;-<span class="st"> 'mean'</span></a>
<a class="sourceLine" id="cb9-17" title="17"><span class="co"># set limits of the map</span></a>
<a class="sourceLine" id="cb9-18" title="18">ylim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">15</span>, <span class="dv">30</span>)</a>
<a class="sourceLine" id="cb9-19" title="19">xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="dv">160</span>, <span class="dv">-105</span>)</a>
<a class="sourceLine" id="cb9-20" title="20"><span class="co"># get outline data for map</span></a>
<a class="sourceLine" id="cb9-21" title="21">w &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/map_data.html">map_data</a></span>(<span class="st">"worldHires"</span>, <span class="dt">ylim =</span> ylim, <span class="dt">xlim =</span> xlim)</a>
<a class="sourceLine" id="cb9-22" title="22"><span class="co"># plot using ggplot</span></a>
<a class="sourceLine" id="cb9-23" title="23">myColor &lt;-<span class="st"> </span>colors<span class="op">$</span>algae</a>
<a class="sourceLine" id="cb9-24" title="24">z &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(alldata,<span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> lon, <span class="dt">y =</span> lat)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-25" title="25"><span class="st">   </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(<span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">colour =</span> mean, <span class="dt">shape =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(missing)), <span class="dt">size =</span> <span class="fl">2.</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-26" title="26"><span class="st">   </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_shape_manual</a></span>(<span class="dt">values =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">19</span>, <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb9-27" title="27">z <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon</a></span>(<span class="dt">data =</span> w, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey80"</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-28" title="28"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-29" title="29"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_colour_gradientn</a></span>(<span class="dt">colours =</span> myColor, <span class="dt">limits =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="fl">0.</span>, <span class="fl">0.32</span>), <span class="st">"Chla"</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb9-30" title="30"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span>(<span class="fl">1.3</span>, <span class="dt">xlim =</span> xlim, <span class="dt">ylim =</span> ylim) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(<span class="st">"Mean chla values at marlin tag locations"</span>)</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/meantrackPlot-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
<div id="comparing-with-the-median" class="section level3">
<h3 class="hasAnchor">
<a href="#comparing-with-the-median" class="anchor"></a>Comparing with the median</h3>
<p>The <code>xtracto</code> routine extracts the environment data in a box (defined by <code>xlen</code> and <code>ylen</code>) around the given location, and calculates statistics of the data in that box. The <span style="color:blue">median chla</span> concentration may make more sense in this situation</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb10-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/colnames">colnames</a></span>(alldata)[<span class="dv">10</span>] &lt;-<span class="st"> 'median'</span></a>
<a class="sourceLine" id="cb10-3" title="3"><span class="co"># plot using ggplot</span></a>
<a class="sourceLine" id="cb10-4" title="4">myColor &lt;-<span class="st"> </span>colors<span class="op">$</span>algae</a>
<a class="sourceLine" id="cb10-5" title="5">z &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(alldata,<span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> lon,<span class="dt">y =</span> lat)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb10-6" title="6"><span class="st">   </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(<span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">colour =</span> median,<span class="dt">shape =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">factor</a></span>(missing)), <span class="dt">size =</span> <span class="fl">2.</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb10-7" title="7"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_shape_manual</a></span>(<span class="dt">values =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">19</span>, <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb10-8" title="8">z <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon</a></span>(<span class="dt">data =</span> w, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey80"</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb10-9" title="9"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb10-10" title="10"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_colour_gradientn</a></span>(<span class="dt">colours =</span> myColor, <span class="dt">limits =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="fl">0.</span>, <span class="fl">0.32</span>), <span class="st">"Chla"</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb10-11" title="11"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span>(<span class="fl">1.3</span>, <span class="dt">xlim =</span> xlim, <span class="dt">ylim =</span> ylim) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(<span class="st">" Median chla values at marlin tag locations"</span>)</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/mediantrackPlot-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
<div id="topography-data" class="section level3">
<h3 class="hasAnchor">
<a href="#topography-data" class="anchor"></a>Topography data</h3>
<p>In addition to satellite data, <code>xtractomatic</code> can access topographic data. As an example we extract and plot the water depth (bathymetry) associated with the trackline.</p>
<p>Get the topography data along the track:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(<span class="st">"xtractomatic"</span>)</a>
<a class="sourceLine" id="cb11-2" title="2">ylim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">15</span>, <span class="dv">30</span>)</a>
<a class="sourceLine" id="cb11-3" title="3">xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="dv">160</span>, <span class="dv">-105</span>)</a>
<a class="sourceLine" id="cb11-4" title="4">topo &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto.html">xtracto</a></span>(<span class="st">"ETOPO180"</span>, tagData<span class="op">$</span>lon, tagData<span class="op">$</span>lat, <span class="dt">xlen =</span> <span class="fl">.1</span>, <span class="dt">ylen =</span> <span class="fl">.1</span>)</a></code></pre></div>
<p>and plot the track:</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(<span class="st">"ggplot2"</span>)</a>
<a class="sourceLine" id="cb12-2" title="2">alldata &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cbind">cbind</a></span>(topo, tagData)</a>
<a class="sourceLine" id="cb12-3" title="3">alldata<span class="op">$</span>lon &lt;-<span class="st"> </span>alldata<span class="op">$</span>lon <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb12-4" title="4"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/colnames">colnames</a></span>(alldata)[<span class="dv">1</span>] &lt;-<span class="st"> 'mean'</span></a>
<a class="sourceLine" id="cb12-5" title="5">z &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(alldata, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> lon,<span class="dt">y =</span> lat)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb12-6" title="6"><span class="st">   </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(<span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">colour =</span> mean), <span class="dt">size =</span> <span class="fl">2.</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb12-7" title="7"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_manual.html">scale_shape_manual</a></span>(<span class="dt">values =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">19</span>, <span class="dv">1</span>))</a>
<a class="sourceLine" id="cb12-8" title="8">z <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon</a></span>(<span class="dt">data =</span> w, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey80"</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb12-9" title="9"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb12-10" title="10"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_colour_gradient</a></span>(<span class="st">"Depth"</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb12-11" title="11"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span>(<span class="fl">1.3</span>, <span class="dt">xlim =</span> xlim, <span class="dt">ylim =</span> ylim) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(<span class="st">"Bathymetry at marlin tag locations"</span>)</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/topotagPlot-1.png" width="576" style="display: block; margin: auto;"></p>
</div>
</div>
<div id="reading-in-tagged-data" class="section level2">
<h2 class="hasAnchor">
<a href="#reading-in-tagged-data" class="anchor"></a>Reading in tagged data</h2>
<p>The above example uses data already converted to <span style="color:red">R</span> format, but clearly the utility of the <code>xtracto</code> function lies in using it with one’s own dataset. This dataset was read in from a text file called <span style="color:blue">Marlin-tag38606.txt</span>, which is also made available when the <code>xtractomatic</code> package is loaded. To be able to refer to this file:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb13-1" title="1"></a>
<a class="sourceLine" id="cb13-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"extdata"</span>, <span class="st">"Marlin-tag38606.txt"</span>, <span class="dt">package =</span> <span class="st">"xtractomatic"</span>)</a></code></pre></div>
<p>The first 5 lines of the file can be viewed:</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1">datafile &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system.file">system.file</a></span>(<span class="st">"extdata"</span>, <span class="st">"Marlin-tag38606.txt"</span>, <span class="dt">package =</span> <span class="st">"xtractomatic"</span>)</a>
<a class="sourceLine" id="cb14-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/system">system</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste</a></span>(<span class="st">"head -n5 "</span>, datafile))</a></code></pre></div>
<p>and read in as follows:</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb15-1" title="1"></a>
<a class="sourceLine" id="cb15-2" title="2">Marlingtag38606 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/read.table">read.csv</a></span>(datafile, <span class="dt">head =</span> <span class="ot">TRUE</span>, <span class="dt">stringsAsFactors =</span> <span class="ot">FALSE</span>, <span class="dt">sep =</span> <span class="st">"</span><span class="ch">\t</span><span class="st">"</span>)</a>
<a class="sourceLine" id="cb15-3" title="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(Marlingtag38606)</a>
<a class="sourceLine" id="cb15-4" title="4"><span class="co">#&gt; 'data.frame':    152 obs. of  7 variables:</span></a>
<a class="sourceLine" id="cb15-5" title="5"><span class="co">#&gt;  $ date  : chr  "4/23/2003" "4/24/2003" "4/30/2003" "5/1/2003" ...</span></a>
<a class="sourceLine" id="cb15-6" title="6"><span class="co">#&gt;  $ lon   : num  204 204 204 204 204 ...</span></a>
<a class="sourceLine" id="cb15-7" title="7"><span class="co">#&gt;  $ lat   : num  19.7 19.8 20.4 20.3 20.3 ...</span></a>
<a class="sourceLine" id="cb15-8" title="8"><span class="co">#&gt;  $ lowLon: num  204 204 204 204 204 ...</span></a>
<a class="sourceLine" id="cb15-9" title="9"><span class="co">#&gt;  $ higLon: num  204 204 204 204 204 ...</span></a>
<a class="sourceLine" id="cb15-10" title="10"><span class="co">#&gt;  $ lowLat: num  19.7 18.8 18.8 18.9 18.9 ...</span></a>
<a class="sourceLine" id="cb15-11" title="11"><span class="co">#&gt;  $ higLat: num  19.7 20.9 21.9 21.7 21.7 ...</span></a></code></pre></div>
<p>The file Marlingtag38606.txt is a “tab” separated file, not a comma seperated file, so the <code>sep</code> option in the <code>read.csv</code> function above indicates that to the function, and <code>stringsAsFactors = FALSE</code> tells the function not to treat the dates as factors.</p>
<p>To be useful the date field, now formatted for example as <code>4/23/2003</code>, needs to be converted to an <span style="color:red">R</span> date field:</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1">Marlintag38606<span class="op">$</span>date &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.Date">as.Date</a></span>(Marlintag38606<span class="op">$</span>date, <span class="dt">format=</span><span class="st">'%m/%d/%Y'</span>)</a></code></pre></div>
<p>The format of the date has to be given because the dates in the file are not in one of the formats recognized by <code>as.Date</code>. A small y (%y) indicates the year has 2 digits (97) while a capital Y (%Y) indicates the year has 4 digits (1997). If your file is in the EU format with commas as decimal points and semicolons as field separators then use read.csv2 rather than read.csv.</p>
<p>This dataset includes the range of the 95% confidence interval for both the latitude and the longitude, which are the last four columns of data. In the example above the search “radius” was read into xtracto was a constant value of 0.2 degrees, but a vector can also be read in. To use the limits given in the file, create the vectors as follows:</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb17-1" title="1">xrad &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(Marlintag38606<span class="op">$</span>higLon <span class="op">-</span><span class="st"> </span>Marlintag38606<span class="op">$</span>lowLon)</a>
<a class="sourceLine" id="cb17-2" title="2">yrad &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(Marlintag38606<span class="op">$</span>higLat <span class="op">-</span><span class="st"> </span>Marlintag38606<span class="op">$</span>lowLat)</a></code></pre></div>
<p>and then use these for the <code>xlen</code> and <code>ylen</code> inputs in <code>xtracto</code>:</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb18-1" title="1">xpos &lt;-<span class="st"> </span>Marlintag38606<span class="op">$</span>lon </a>
<a class="sourceLine" id="cb18-2" title="2">ypos &lt;-<span class="st"> </span>Marlintag38606<span class="op">$</span>lat </a>
<a class="sourceLine" id="cb18-3" title="3">tpos &lt;-<span class="st"> </span>Marlintag38606<span class="op">$</span>date</a>
<a class="sourceLine" id="cb18-4" title="4">swchl &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto.html">xtracto</a></span>(xpos, ypos, tpos, <span class="st">"swchla8day"</span>, xrad, yrad)</a></code></pre></div>
</div>
<div id="using-xtracto_3d" class="section level2">
<h2 class="hasAnchor">
<a href="#using-xtracto_3d" class="anchor"></a>Using <code>xtracto_3D</code>
</h2>
<div id="comparing-chlorophyll-estimates-from-different-satellites" class="section level3">
<h3 class="hasAnchor">
<a href="#comparing-chlorophyll-estimates-from-different-satellites" class="anchor"></a>Comparing chlorophyll estimates from different satellites</h3>
<p>This example extracts a time-series of monthly satellite <span style="color:red">chlorophyll</span> data for the period 1998-2014 from three different satellites ( <span style="color:red">SeaWIFS</span>, <span style="color:red">MODIS</span> and <span style="color:red">VIIRS</span> ), using the <code>xtracto_3D</code> function. The extract is for an area off the coast of California. <code>xtracto_3D</code> extracts data in a 3D bounding box where <code>xpos</code> has the minimum and maximum <span style="color:red">longitude</span>, <code>ypos</code> has the minimum and maximum <span style="color:red">latitude</span>, and <code>tpos</code> has the starting and ending <span style="color:red">time</span>, given as “YYY-MM-DD”, describing the bounding box.</p>
<p>First we define the longitude, latitude and temporal boundaries of the box:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb19-1" title="1">xpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">235</span>, <span class="dv">240</span>)</a>
<a class="sourceLine" id="cb19-2" title="2">ypos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">36</span>, <span class="dv">39</span>)</a>
<a class="sourceLine" id="cb19-3" title="3">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">'1998-01-01'</span>, <span class="st">'2014-11-30'</span>) </a></code></pre></div>
<p>The extract will contain data at all of the longitudes, latitudes and times in the requested dataset that are within the given bounds.</p>
<p>If we run the <code>xtracto_3D</code> using the full temporal contraints defined above for <span style="color:red">SeaWiFS</span> we get an error:</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb20-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb20-2" title="2">chlSeaWiFS &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">'swchlamday'</span>, xpos, ypos, <span class="dt">tpos =</span> tpos )</a>
<a class="sourceLine" id="cb20-3" title="3"><span class="co">#&gt; [1] "tpos  (time) has elements out of range of the dataset"</span></a>
<a class="sourceLine" id="cb20-4" title="4"><span class="co">#&gt; [1] "time range in tpos"</span></a>
<a class="sourceLine" id="cb20-5" title="5"><span class="co">#&gt; [1] "1998-01-01,2014-11-30"</span></a>
<a class="sourceLine" id="cb20-6" title="6"><span class="co">#&gt; [1] "time range in ERDDAP data"</span></a>
<a class="sourceLine" id="cb20-7" title="7"><span class="co">#&gt; [1] "1997-09-16,2010-12-16 12:00:00"</span></a>
<a class="sourceLine" id="cb20-8" title="8"><span class="co">#&gt; Error in xtracto_3D("swchlamday", xpos, ypos, tpos = tpos): Coordinates out of dataset bounds - see messages above</span></a></code></pre></div>
<p>The error occurs because the time-range specified is outside of the time-bounds of the requested dataset ( <span style="color:red">SeaWIFS</span> data stopped in 2010). The error message generated by <code>xtracto_3D</code> explains this, and gives the temporal boundaries of the dataset. A simple way to extract to the end of a dataset is to use “last” (see <a href="#lastTimes">Taking advantage of “last times”</a>):</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb21-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb21-2" title="2">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"1998-01-16"</span>, <span class="st">"last"</span>)</a>
<a class="sourceLine" id="cb21-3" title="3">SeaWiFS &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">'swchlamday'</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a></code></pre></div>
<p>A similar extract can be made for the <span style="color:red">MODIS</span> dataset. We know that the time-range of the <span style="color:red">MODIS</span> dataset is also smaller than that defined by <code>tpos</code>. We can determine the exact bounds of the <span style="color:red">MODIS</span> dataset by using the <code>getInfo</code> function:</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb22-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb22-2" title="2"><span class="kw"><a href="../reference/getInfo.html">getInfo</a></span>(<span class="st">'mhchlamday'</span>)</a>
<a class="sourceLine" id="cb22-3" title="3"><span class="co">#&gt; List of 19</span></a>
<a class="sourceLine" id="cb22-4" title="4"><span class="co">#&gt;  $ dtypename       : chr "mhchlamday"</span></a>
<a class="sourceLine" id="cb22-5" title="5"><span class="co">#&gt;  $ datasetname     : chr "erdMH1chlamday"</span></a>
<a class="sourceLine" id="cb22-6" title="6"><span class="co">#&gt;  $ longname        : chr "Chlorophyll-a, Aqua MODIS, NPP, L3SMI, Global, Science Quality (Monthly Composite)"</span></a>
<a class="sourceLine" id="cb22-7" title="7"><span class="co">#&gt;  $ varname         : chr "chlorophyll"</span></a>
<a class="sourceLine" id="cb22-8" title="8"><span class="co">#&gt;  $ hasAlt          : logi FALSE</span></a>
<a class="sourceLine" id="cb22-9" title="9"><span class="co">#&gt;  $ latSouth        : logi FALSE</span></a>
<a class="sourceLine" id="cb22-10" title="10"><span class="co">#&gt;  $ lon360          : logi FALSE</span></a>
<a class="sourceLine" id="cb22-11" title="11"><span class="co">#&gt;  $ minLongitude    : num -180</span></a>
<a class="sourceLine" id="cb22-12" title="12"><span class="co">#&gt;  $ maxLongitude    : num 180</span></a>
<a class="sourceLine" id="cb22-13" title="13"><span class="co">#&gt;  $ longitudeSpacing: num 0.0417</span></a>
<a class="sourceLine" id="cb22-14" title="14"><span class="co">#&gt;  $ minLatitude     : num -90</span></a>
<a class="sourceLine" id="cb22-15" title="15"><span class="co">#&gt;  $ maxLatitude     : num 90</span></a>
<a class="sourceLine" id="cb22-16" title="16"><span class="co">#&gt;  $ latitudeSpacing : num -0.0417</span></a>
<a class="sourceLine" id="cb22-17" title="17"><span class="co">#&gt;  $ minAltitude     : num NA</span></a>
<a class="sourceLine" id="cb22-18" title="18"><span class="co">#&gt;  $ maxAltitude     : num NA</span></a>
<a class="sourceLine" id="cb22-19" title="19"><span class="co">#&gt;  $ minTime         : chr "2003-01-16"</span></a>
<a class="sourceLine" id="cb22-20" title="20"><span class="co">#&gt;  $ maxTime         : chr "2019-01-16"</span></a>
<a class="sourceLine" id="cb22-21" title="21"><span class="co">#&gt;  $ timeSpacing     : num NA</span></a>
<a class="sourceLine" id="cb22-22" title="22"><span class="co">#&gt;  $ infoURL         : chr "http://oceancolor.gsfc.nasa.gov/"</span></a></code></pre></div>
<p>which gives us the min and max time of the dataset, which we can be used in the call (or use “last” as above):</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb23-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb23-2" title="2">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">'2003-01-16'</span>, <span class="st">"last"</span>)</a>
<a class="sourceLine" id="cb23-3" title="3">MODIS &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">'mhchlamday'</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a></code></pre></div>
<p>Similarly we can extract data from the <span style="color:red">VIIRS</span> dataset.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb24-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb24-2" title="2">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"2012-01-15"</span>, <span class="st">"last"</span>)</a>
<a class="sourceLine" id="cb24-3" title="3">VIIRS &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">'erdVH3chlamday'</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a></code></pre></div>
<p><code>xtracto_3d</code> returns a list of the form:</p>
<ul>
<li>extract$data : num [longitude, latitude, time]</li>
<li>extract$varname : character string with the name of the variable</li>
<li>extract$datasetname: character string of the ERDDAP dataset ID</li>
<li>extract$latitude : num [latitude] latitudes of extract</li>
<li>extract$longitude : num [longitude] longitude of extact</li>
<li>extract$time : chr [time] times of extract</li>
<li>extract$altitude : num altitude of extract</li>
</ul>
<p>in this case the <span style="color:red">varname</span> is <span style="color:red">chla</span>, the <span style="color:red">ERDDAP</span> <code>datasetID</code> is <span style="color:red">erdVH3chlamday</span>, and <span style="color:red">data</span> contains the data on the grid defined by <span style="color:red">longitude</span>, <span style="color:red">latitude</span> and <span style="color:red">time</span>. The data from the different satellites can be compared by mapping the values for a given time period, which we cna do using the function <code>plotBBox()</code>.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb25-1" title="1">mapFrame &lt;-<span class="st"> </span><span class="cf">function</span>(longitude, latitude, chla){</a>
<a class="sourceLine" id="cb25-2" title="2">  dims &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/dim">dim</a></span>(chla)</a>
<a class="sourceLine" id="cb25-3" title="3">  chla &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/array">array</a></span>(chla, dims[<span class="dv">1</span>] <span class="op">*</span><span class="st"> </span>dims[<span class="dv">2</span>])</a>
<a class="sourceLine" id="cb25-4" title="4">  longitude &lt;-<span class="st"> </span>longitude <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb25-5" title="5">  chlaFrame &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/expand.grid">expand.grid</a></span>(<span class="dt">x =</span> longitude, <span class="dt">y =</span> latitude)</a>
<a class="sourceLine" id="cb25-6" title="6">  chlaFrame<span class="op">$</span>chla &lt;-<span class="st"> </span>chla</a>
<a class="sourceLine" id="cb25-7" title="7">  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/function">return</a></span>(chlaFrame)</a>
<a class="sourceLine" id="cb25-8" title="8">}</a></code></pre></div>
<p>and also define a helper function <code>plotFrame</code> to plot the data:</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb26-1" title="1">plotFrame &lt;-<span class="st"> </span><span class="cf">function</span>(chlaFrame, xlim, ylim, title, <span class="dt">logplot =</span> <span class="ot">TRUE</span>){</a>
<a class="sourceLine" id="cb26-2" title="2">  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(mapdata)</a>
<a class="sourceLine" id="cb26-3" title="3">  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb26-4" title="4">  w &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/map_data.html">map_data</a></span>(<span class="st">"worldHires"</span>, <span class="dt">ylim =</span> ylim, <span class="dt">xlim =</span> xlim)</a>
<a class="sourceLine" id="cb26-5" title="5">  myplot &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(<span class="dt">data =</span> chlaFrame, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y, <span class="dt">fill =</span> chla)) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-6" title="6"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_raster</a></span>(<span class="dt">interpolate =</span> <span class="ot">FALSE</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-7" title="7"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon</a></span>(<span class="dt">data =</span> w, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey80"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-8" title="8"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span>(<span class="st">"latitude"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span>(<span class="st">"longitude"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-9" title="9"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span>(<span class="fl">1.3</span>, <span class="dt">xlim =</span> xlim, <span class="dt">ylim =</span> ylim)</a>
<a class="sourceLine" id="cb26-10" title="10">  <span class="cf">if</span> (logplot) {</a>
<a class="sourceLine" id="cb26-11" title="11">     my.col &lt;-<span class="st"> </span>colors<span class="op">$</span>algae</a>
<a class="sourceLine" id="cb26-12" title="12">    myplot &lt;-<span class="st"> </span>myplot <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradientn</a></span>(<span class="dt">colours =</span> my.col, <span class="dt">na.value =</span> <span class="ot">NA</span>, <span class="dt">limits =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="dv">2</span>, <span class="fl">4.5</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-13" title="13"><span class="st">      </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(title)</a>
<a class="sourceLine" id="cb26-14" title="14">    }<span class="cf">else</span>{</a>
<a class="sourceLine" id="cb26-15" title="15">      my.col &lt;-<span class="st"> </span>colors<span class="op">$</span>algae</a>
<a class="sourceLine" id="cb26-16" title="16">     myplot &lt;-<span class="st"> </span>myplot <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradientn</a></span>(<span class="dt">colours =</span> my.col, <span class="dt">na.value =</span> <span class="ot">NA</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb26-17" title="17"><span class="st">       </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(title)</a>
<a class="sourceLine" id="cb26-18" title="18">  }</a>
<a class="sourceLine" id="cb26-19" title="19">  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/function">return</a></span>(myplot)</a>
<a class="sourceLine" id="cb26-20" title="20">}</a></code></pre></div>
<p>We examine <span style="color:red">chlorophyll</span> in June 2012 a period when VIIRS and MODIS both had data. Starting with <span style="color:red">VIIRS</span>:</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb27-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(lubridate)</a>
<a class="sourceLine" id="cb27-2" title="2"><span class="co">#&gt; Loading required package: lubridate</span></a>
<a class="sourceLine" id="cb27-3" title="3"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb27-4" title="4"><span class="co">#&gt; Attaching package: 'lubridate'</span></a>
<a class="sourceLine" id="cb27-5" title="5"><span class="co">#&gt; The following object is masked from 'package:base':</span></a>
<a class="sourceLine" id="cb27-6" title="6"><span class="co">#&gt; </span></a>
<a class="sourceLine" id="cb27-7" title="7"><span class="co">#&gt;     date</span></a>
<a class="sourceLine" id="cb27-8" title="8">xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">235</span>, <span class="dv">240</span>) <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb27-9" title="9">ylim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">36</span>, <span class="dv">39</span>)</a>
<a class="sourceLine" id="cb27-10" title="10">ttext &lt;-<span class="st"> </span>VIIRS<span class="op">$</span>time[<span class="kw"><a href="http://lubridate.tidyverse.org/reference/month.html">month</a></span>(VIIRS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">6</span> <span class="op">&amp;</span><span class="st"> </span><span class="kw"><a href="http://lubridate.tidyverse.org/reference/year.html">year</a></span>(VIIRS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">2012</span>]</a>
<a class="sourceLine" id="cb27-11" title="11">chlaFrame &lt;-<span class="st"> </span><span class="kw">mapFrame</span>(VIIRS<span class="op">$</span>longitude,VIIRS<span class="op">$</span>latitude,VIIRS<span class="op">$</span>data[, , <span class="kw"><a href="http://lubridate.tidyverse.org/reference/month.html">month</a></span>(VIIRS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">6</span> <span class="op">&amp;</span><span class="st"> </span><span class="kw"><a href="http://lubridate.tidyverse.org/reference/year.html">year</a></span>(VIIRS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">2012</span>])</a>
<a class="sourceLine" id="cb27-12" title="12">chlaPlot &lt;-<span class="st"> </span><span class="kw">plotFrame</span>(chlaFrame, xlim, ylim, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste</a></span>(<span class="st">"VIIRS chla"</span>, ttext), <span class="dt">logplot =</span> <span class="ot">FALSE</span>)</a>
<a class="sourceLine" id="cb27-13" title="13">chlaPlot</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/VIIRSPlot-1.png" width="480" style="display: block; margin: auto;"></p>
<p><span style="color:red">Chlorophyll</span> values are highly skewed, with low values most places and times, and then for some locations very high values. For this reason <span style="color:red">log(chlorophyll)</span> is usually plotted.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb28-1" title="1">xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">235</span>, <span class="dv">240</span>) <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb28-2" title="2">ylim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">36</span>, <span class="dv">39</span>)</a>
<a class="sourceLine" id="cb28-3" title="3">chlalogFrame &lt;-<span class="st"> </span><span class="kw">mapFrame</span>(VIIRS<span class="op">$</span>longitude,VIIRS<span class="op">$</span>latitude,</a>
<a class="sourceLine" id="cb28-4" title="4">                       <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Log">log</a></span>(VIIRS<span class="op">$</span>data[, , <span class="kw"><a href="http://lubridate.tidyverse.org/reference/month.html">month</a></span>(VIIRS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">6</span> <span class="op">&amp;</span><span class="st"> </span><span class="kw"><a href="http://lubridate.tidyverse.org/reference/year.html">year</a></span>(VIIRS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">2012</span>]))</a>
<a class="sourceLine" id="cb28-5" title="5">chlalogPlot &lt;-<span class="st"> </span><span class="kw">plotFrame</span>(chlalogFrame, xlim, ylim, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste</a></span>(<span class="st">"VIIRS log(chla)"</span>, ttext))</a>
<a class="sourceLine" id="cb28-6" title="6">chlalogPlot</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/VIIRSLogPlot-1.png" width="480" style="display: block; margin: auto;"></p>
<p>And also for <span style="color:red">MODIS</span>:</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb29-1" title="1">xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">235</span>, <span class="dv">240</span>) <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb29-2" title="2">ylim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">36</span>, <span class="dv">39</span>)</a>
<a class="sourceLine" id="cb29-3" title="3">ttext &lt;-<span class="st"> </span>MODIS<span class="op">$</span>time[<span class="kw"><a href="http://lubridate.tidyverse.org/reference/month.html">month</a></span>(MODIS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">6</span> <span class="op">&amp;</span><span class="st"> </span><span class="kw"><a href="http://lubridate.tidyverse.org/reference/year.html">year</a></span>(MODIS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">2012</span>]</a>
<a class="sourceLine" id="cb29-4" title="4">chlalogFrame &lt;-<span class="st"> </span><span class="kw">mapFrame</span>(MODIS<span class="op">$</span>longitude, MODIS<span class="op">$</span>latitude,</a>
<a class="sourceLine" id="cb29-5" title="5">                       <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Log">log</a></span>(MODIS<span class="op">$</span>data[, , <span class="kw"><a href="http://lubridate.tidyverse.org/reference/month.html">month</a></span>(MODIS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">6</span> <span class="op">&amp;</span><span class="st"> </span><span class="kw"><a href="http://lubridate.tidyverse.org/reference/year.html">year</a></span>(MODIS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">2012</span>]))</a>
<a class="sourceLine" id="cb29-6" title="6">chlalogPlot &lt;-<span class="st"> </span><span class="kw">plotFrame</span>(chlalogFrame, xlim, ylim, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste</a></span>(<span class="st">"MODIS log(chla)"</span>, ttext))</a>
<a class="sourceLine" id="cb29-7" title="7">chlalogPlot</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/MODISLogPlot-1.png" width="480" style="display: block; margin: auto;"></p>
<p><span style="color:red">SeaWiFS</span> stopped functioning at the end of 2010, so we look at June, 2010:</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb30-1" title="1">xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">235</span>, <span class="dv">240</span>) <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb30-2" title="2">ylim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">36</span>, <span class="dv">39</span>)</a>
<a class="sourceLine" id="cb30-3" title="3">ttext &lt;-<span class="st"> </span>SeaWiFS<span class="op">$</span>time[<span class="kw"><a href="http://lubridate.tidyverse.org/reference/month.html">month</a></span>(SeaWiFS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">6</span> <span class="op">&amp;</span><span class="st"> </span><span class="kw"><a href="http://lubridate.tidyverse.org/reference/year.html">year</a></span>(SeaWiFS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>]</a>
<a class="sourceLine" id="cb30-4" title="4">chlalogFrame &lt;-<span class="st"> </span><span class="kw">mapFrame</span>(SeaWiFS<span class="op">$</span>longitude, SeaWiFS<span class="op">$</span>latitude,</a>
<a class="sourceLine" id="cb30-5" title="5">                       <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Log">log</a></span>(SeaWiFS<span class="op">$</span>data[, , <span class="kw"><a href="http://lubridate.tidyverse.org/reference/month.html">month</a></span>(SeaWiFS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">6</span> <span class="op">&amp;</span><span class="st"> </span><span class="kw"><a href="http://lubridate.tidyverse.org/reference/year.html">year</a></span>(SeaWiFS<span class="op">$</span>time) <span class="op">==</span><span class="st"> </span><span class="dv">2010</span>]))</a>
<a class="sourceLine" id="cb30-6" title="6">chlalogPlot &lt;-<span class="st"> </span><span class="kw">plotFrame</span>(chlalogFrame, xlim, ylim, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste</a></span>(<span class="st">"SeaWiFS log(chla)"</span>, ttext))</a>
<a class="sourceLine" id="cb30-7" title="7">chlalogPlot</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/SeaWiFSLogPlot-1.png" width="480" style="display: block; margin: auto;"></p>
<p>We can also look at changes in <span style="color:red">log(chlorophyll)</span> over time for a given region. We examine a higly productive region just north of San Francisco, with limits (38N, 38.5N) and (123.5W, 123W).</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb31-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb31-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(mapdata)</a>
<a class="sourceLine" id="cb31-3" title="3">xlim1 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="fl">123.5</span>, <span class="dv">-123</span>) <span class="op">+</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb31-4" title="4">ylim1 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">38</span>, <span class="fl">38.5</span>)</a>
<a class="sourceLine" id="cb31-5" title="5">w &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/map_data.html">map_data</a></span>(<span class="st">"worldHires"</span>, <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="fl">37.5</span>, <span class="dv">39</span>), <span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="fl">123.5</span>, <span class="fl">-122.</span>))</a>
<a class="sourceLine" id="cb31-6" title="6">z &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon</a></span>(<span class="dt">data =</span> w, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey80"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb31-7" title="7"><span class="st">   </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb31-8" title="8"><span class="st">   </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span>(<span class="fl">1.3</span>, <span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="fl">123.5</span>, <span class="fl">-122.</span>), <span class="dt">ylim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="fl">37.5</span>, <span class="dv">39</span>))</a>
<a class="sourceLine" id="cb31-9" title="9">z <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_rect</a></span>(<span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">xmin =</span> <span class="fl">-123.5</span>, <span class="dt">xmax =</span> <span class="fl">-123.</span>, <span class="dt">ymin =</span> <span class="fl">38.</span>, <span class="dt">ymax =</span> <span class="fl">38.5</span>), <span class="dt">colour =</span> <span class="st">"black"</span>, <span class="dt">alpha =</span> <span class="fl">0.</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb31-10" title="10"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(<span class="st">"Location of chla averaging"</span>)</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/chlaAvgset-1.png" width="480" style="display: block; margin: auto;"></p>
<p>We define a helper function <code>chlaAvg</code> which finds the <span style="color:red">latitudes</span> and <span style="color:red">longitudes</span> in the datasets that are closest to the given limits, extracts the subset that is within that region, and then averages over the region to create a time series.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb32-1" title="1">chlaAvg &lt;-<span class="st"> </span><span class="cf">function</span>(longitude, latitude, chlaData, xlim, ylim, sTimes){</a>
<a class="sourceLine" id="cb32-2" title="2">  xIndex &lt;-<span class="st"> </span>xlim</a>
<a class="sourceLine" id="cb32-3" title="3">  yIndex &lt;-<span class="st"> </span>ylim</a>
<a class="sourceLine" id="cb32-4" title="4">  yIndex[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(latitude <span class="op">-</span><span class="st"> </span>ylim[<span class="dv">1</span>]))</a>
<a class="sourceLine" id="cb32-5" title="5">  yIndex[<span class="dv">2</span>] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(latitude <span class="op">-</span><span class="st"> </span>ylim[<span class="dv">2</span>]))</a>
<a class="sourceLine" id="cb32-6" title="6">  xIndex[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(longitude <span class="op">-</span><span class="st"> </span>xlim[<span class="dv">1</span>]))</a>
<a class="sourceLine" id="cb32-7" title="7">  xIndex[<span class="dv">2</span>] &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(longitude <span class="op">-</span><span class="st"> </span>xlim[<span class="dv">2</span>]))</a>
<a class="sourceLine" id="cb32-8" title="8">  tempData &lt;-<span class="st"> </span>chlaData[xIndex[<span class="dv">1</span>]<span class="op">:</span>xIndex[<span class="dv">2</span>], yIndex[<span class="dv">1</span>]<span class="op">:</span>yIndex[<span class="dv">2</span>],]</a>
<a class="sourceLine" id="cb32-9" title="9">  chlaAvg &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/apply">apply</a></span>(tempData, <span class="dv">3</span>, mean, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>)</a>
<a class="sourceLine" id="cb32-10" title="10">  chlaAvg &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">chla =</span> chlaAvg, <span class="dt">time =</span> sTimes)</a>
<a class="sourceLine" id="cb32-11" title="11"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/function">return</a></span>(chlaAvg)</a>
<a class="sourceLine" id="cb32-12" title="12">}</a></code></pre></div>
<p>We use <code>chlaAvg</code> to extract the three time series over the region, combine them and plot the result.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb33-1" title="1">xlim1 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="fl">123.5</span>, <span class="dv">-123</span>) <span class="op">+</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb33-2" title="2">ylim1 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">38</span>, <span class="fl">38.5</span>)</a>
<a class="sourceLine" id="cb33-3" title="3"><span class="co"># Get both the average, and the average of log transformed chl for each point in the time series </span></a>
<a class="sourceLine" id="cb33-4" title="4">SeaWiFSavg &lt;-<span class="st"> </span><span class="kw">chlaAvg</span>(SeaWiFS<span class="op">$</span>longitude, SeaWiFS<span class="op">$</span>latitude, SeaWiFS<span class="op">$</span>data, xlim1, ylim1,SeaWiFS<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb33-5" title="5">SeaWiFSlog &lt;-<span class="st"> </span><span class="kw">chlaAvg</span>(SeaWiFS<span class="op">$</span>longitude, SeaWiFS<span class="op">$</span>latitude, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Log">log</a></span>(SeaWiFS<span class="op">$</span>data), xlim1, ylim1, SeaWiFS<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb33-6" title="6"><span class="co"># Run the same steps again for the MODIS and VIIRS datasets</span></a>
<a class="sourceLine" id="cb33-7" title="7">MODISavg &lt;-<span class="st"> </span><span class="kw">chlaAvg</span>(MODIS<span class="op">$</span>longitude, MODIS<span class="op">$</span>latitude, MODIS<span class="op">$</span>data, xlim1, ylim1, MODIS<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb33-8" title="8">MODISlog &lt;-<span class="st"> </span><span class="kw">chlaAvg</span>(MODIS<span class="op">$</span>longitude, MODIS<span class="op">$</span>latitude, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Log">log</a></span>(MODIS<span class="op">$</span>data), xlim1, ylim1, MODIS<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb33-9" title="9"><span class="co"># run the same for VIIRS</span></a>
<a class="sourceLine" id="cb33-10" title="10">VIIRSavg &lt;-<span class="st"> </span><span class="kw">chlaAvg</span>(VIIRS<span class="op">$</span>longitude, VIIRS<span class="op">$</span>latitude, VIIRS<span class="op">$</span>data, xlim1, ylim1, VIIRS<span class="op">$</span>time)</a>
<a class="sourceLine" id="cb33-11" title="11">VIIRSlog &lt;-<span class="st"> </span><span class="kw">chlaAvg</span>(VIIRS<span class="op">$</span>longitude, VIIRS<span class="op">$</span>latitude, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Log">log</a></span>(VIIRS<span class="op">$</span>data), xlim1, ylim1, VIIRS<span class="op">$</span>time)</a></code></pre></div>
<p>First the raw <span style="color:red">chla</span> values:</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb34-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb34-2" title="2">Chla &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cbind">rbind</a></span>(VIIRSavg, MODISavg, SeaWiFSavg)</a>
<a class="sourceLine" id="cb34-3" title="3">Chla<span class="op">$</span>sat &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="st">"VIIRS"</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(VIIRSavg)), <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="st">"MODIS"</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(MODISavg)), <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="st">"SeaWIF"</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(SeaWiFSavg)))</a>
<a class="sourceLine" id="cb34-4" title="4">Chla<span class="op">$</span>sat &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">as.factor</a></span>(Chla<span class="op">$</span>sat)</a>
<a class="sourceLine" id="cb34-5" title="5"><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(<span class="dt">data =</span> Chla, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(time, chla, <span class="dt">colour =</span> sat)) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span>(<span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>()</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/plotChlaTS-1.png" width="768" style="display: block; margin: auto;"></p>
<p>and then <span style="color:red">log(chla)</span>:</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb35-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb35-2" title="2">logChla &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cbind">rbind</a></span>(VIIRSlog, MODISlog, SeaWiFSlog)</a>
<a class="sourceLine" id="cb35-3" title="3">logChla<span class="op">$</span>sat &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="st">"VIIRS"</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(VIIRSlog)), <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="st">"MODIS"</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(MODISlog)), <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="st">"SeaWIF"</span>,    <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(SeaWiFSlog)))</a>
<a class="sourceLine" id="cb35-4" title="4">logChla<span class="op">$</span>sat &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">as.factor</a></span>(Chla<span class="op">$</span>sat)</a>
<a class="sourceLine" id="cb35-5" title="5"><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(<span class="dt">data =</span> logChla, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(time, chla, <span class="dt">colour =</span> sat)) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span>(<span class="dt">na.rm =</span> <span class="ot">TRUE</span>)  <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>()</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/plotlogChlaTS-1.png" width="768" style="display: block; margin: auto;"></p>
</div>
<div id="upwelling" class="section level3">
<h3 class="hasAnchor">
<a href="#upwelling" class="anchor"></a>Upwelling</h3>
<p><span style="color:red">ERD</span> for many years has produced 6-hourly <span style="color:red">Bakun upwelling indices</span> at 15 set locations. But suppose you want the values at a different location? To do this we define a function <code>upwell</code> that rotates <span style="color:red">Ekman transport</span> values to obtain the offshore component (<span style="color:red">upwelling index</span>), and also define a function <code>plotUpwell</code> to plot <span style="color:red">upwelling</span>. <code>xtracto_3D</code> can download <span style="color:rede">Ekman transport</span> calculated from <span style="color:red">Fleet Numerical Meteorlogical and Oceanographic Center (FNMOC)</span> pressure fields:</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb36-1" title="1">upwell &lt;-<span class="st"> </span><span class="cf">function</span>(ektrx, ektry, coast_angle){</a>
<a class="sourceLine" id="cb36-2" title="2">   pi &lt;-<span class="st"> </span><span class="fl">3.1415927</span></a>
<a class="sourceLine" id="cb36-3" title="3">   degtorad &lt;-<span class="st"> </span>pi<span class="op">/</span><span class="fl">180.</span></a>
<a class="sourceLine" id="cb36-4" title="4">   alpha &lt;-<span class="st"> </span>(<span class="dv">360</span> <span class="op">-</span><span class="st"> </span>coast_angle) <span class="op">*</span><span class="st"> </span>degtorad</a>
<a class="sourceLine" id="cb36-5" title="5">   s1 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Trig">cos</a></span>(alpha)</a>
<a class="sourceLine" id="cb36-6" title="6">   t1 &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Trig">sin</a></span>(alpha)</a>
<a class="sourceLine" id="cb36-7" title="7">   s2 &lt;-<span class="st"> </span><span class="dv">-1</span> <span class="op">*</span><span class="st"> </span>t1</a>
<a class="sourceLine" id="cb36-8" title="8">   t2 &lt;-<span class="st"> </span>s1</a>
<a class="sourceLine" id="cb36-9" title="9">   perp &lt;-<span class="st"> </span>s1 <span class="op">*</span><span class="st"> </span>ektrx <span class="op">+</span><span class="st"> </span>t1 <span class="op">*</span><span class="st"> </span>ektry</a>
<a class="sourceLine" id="cb36-10" title="10">   para &lt;-<span class="st"> </span>s2 <span class="op">*</span><span class="st"> </span>ektrx <span class="op">+</span><span class="st"> </span>t2 <span class="op">*</span><span class="st"> </span>ektry</a>
<a class="sourceLine" id="cb36-11" title="11"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/function">return</a></span>(perp<span class="op">/</span><span class="dv">10</span>)</a>
<a class="sourceLine" id="cb36-12" title="12">}</a></code></pre></div>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb37-1" title="1">plotUpwell &lt;-<span class="st"> </span><span class="cf">function</span>(upwelling, upDates){</a>
<a class="sourceLine" id="cb37-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb37-3" title="3">temp &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">upwelling =</span> upwelling, <span class="dt">time =</span> upDates)</a>
<a class="sourceLine" id="cb37-4" title="4"><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(temp, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(time, upwelling)) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span>(<span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>()</a>
<a class="sourceLine" id="cb37-5" title="5">}</a></code></pre></div>
<p>We calculate 6-hourly upwelling at (37,-122) for the year 2005 and use the coast angle that <span style="color:red">ERD</span> uses for (36N , 122W) which is 152 degrees.</p>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb38-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb38-2" title="2">xpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">238</span>, <span class="dv">238</span>)</a>
<a class="sourceLine" id="cb38-3" title="3">ypos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">37</span>, <span class="dv">37</span>)</a>
<a class="sourceLine" id="cb38-4" title="4">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"2005-01-01"</span>, <span class="st">"2005-12-31"</span>)</a>
<a class="sourceLine" id="cb38-5" title="5">ektrx &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">"erdlasFnTran6ektrx"</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a>
<a class="sourceLine" id="cb38-6" title="6">ektry &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">"erdlasFnTran6ektry"</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a>
<a class="sourceLine" id="cb38-7" title="7">upwelling &lt;-<span class="st"> </span><span class="kw">upwell</span>(ektrx<span class="op">$</span>data, ektry<span class="op">$</span>data, <span class="dv">152</span>)</a></code></pre></div>
<p>A plot of the result:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb39-1" title="1"><span class="kw">plotUpwell</span>(upwelling, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.Date">as.Date</a></span>(ektrx<span class="op">$</span>time))</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/plotUpw1-1.png" width="672" style="display: block; margin: auto;"></p>
<p>The one very low downwelling value distorts the plot, so values &lt; -500 are set to NA and the data are replotted:</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb40-1" title="1">tempUpw &lt;-<span class="st"> </span>upwelling</a>
<a class="sourceLine" id="cb40-2" title="2">tempUpw[tempUpw <span class="op">&lt;</span><span class="st"> </span><span class="dv">-500</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb40-3" title="3"><span class="kw">plotUpwell</span>(tempUpw, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.Date">as.Date</a></span>(ektrx<span class="op">$</span>time))</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/plotUpw3-1.png" width="672" style="display: block; margin: auto;"></p>
<p>In 2005 there was a large die-off of sea animals and many felt that is was due to an anomalously delayed <span style="color:red">upwelling</span>. Let’s compare <span style="color:red">upwelling</span> in 2005 at that location with <span style="color:red">upwelling</span> in 1977:</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb41-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb41-2" title="2">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"1977-01-01"</span>, <span class="st">"1977-12-31"</span>)</a>
<a class="sourceLine" id="cb41-3" title="3">ektrx77 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">"erdlasFnTran6ektrx"</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a>
<a class="sourceLine" id="cb41-4" title="4">ektry77 &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">"erdlasFnTran6ektry"</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a>
<a class="sourceLine" id="cb41-5" title="5">upwelling77 &lt;-<span class="st"> </span><span class="kw">upwell</span>(ektrx77<span class="op">$</span>data, ektry77<span class="op">$</span>data, <span class="dv">152</span>)</a>
<a class="sourceLine" id="cb41-6" title="6"><span class="co"># remove the one big storm at the end</span></a>
<a class="sourceLine" id="cb41-7" title="7">tempUpw &lt;-<span class="st"> </span>upwelling77</a>
<a class="sourceLine" id="cb41-8" title="8">tempUpw[tempUpw <span class="op">&lt;</span><span class="st"> </span><span class="dv">-500</span>] &lt;-<span class="st"> </span><span class="ot">NA</span></a>
<a class="sourceLine" id="cb41-9" title="9"><span class="kw">plotUpwell</span>(tempUpw, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.Date">as.Date</a></span>(ektrx77<span class="op">$</span>time))</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/plotUpw77-1.png" width="672" style="display: block; margin: auto;"></p>
<p>While we have not looked at all areas along the coast, at least for this location it is difficult to see upwelling in 2005 as being any more delayed than in 1977 when there was not the same affect on animals.</p>
</div>
<div id="comparisons-of-wind-stress" class="section level3">
<h3 class="hasAnchor">
<a href="#comparisons-of-wind-stress" class="anchor"></a>Comparisons of Wind Stress</h3>
<p>A problem faced when using satellite based estimates of <span style="color:red">wind stress</span> is that the <span style="color:red">QuikSCAT</span> based estimates start in 1999-07-21 and end in 2009-11-19, while the <span style="color:red">ASCAT</span> based estimates start in 2009-10-03 and are ongoing. A comparison of the data over the period of overlap would be of interest.</p>
<p>We examine <span style="color:red">north-south wind stress (tauy)</span> over the period of overlap at (36N, 121W) (we go a little more offshore because the satellite data is not resolved close to the coast), and compare 3-day composites of <span style="color:red">tauy</span>. In this region <span style="color:red">tauy</span> is the main component of <span style="color:red">upwelling</span> as the coastline runs almost north-south and the winds are mostly from the north or north-west.</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb42-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb42-2" title="2">xpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">237</span>, <span class="dv">237</span>)</a>
<a class="sourceLine" id="cb42-3" title="3">ypos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">36</span>, <span class="dv">36</span>)</a>
<a class="sourceLine" id="cb42-4" title="4">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"2009-10-04"</span>, <span class="st">"2009-11-19"</span>)</a>
<a class="sourceLine" id="cb42-5" title="5">ascat &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">"erdQAstress3daytauy"</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a>
<a class="sourceLine" id="cb42-6" title="6">quikscat &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">"erdQSstress3daytauy"</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a></code></pre></div>
<p>Plotting the result</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb43-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb43-2" title="2">ascatStress &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">stress =</span> ascat<span class="op">$</span>data, <span class="dt">time =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.Date">as.Date</a></span>(ascat<span class="op">$</span>time))</a>
<a class="sourceLine" id="cb43-3" title="3">quikscatStress &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/data.frame">data.frame</a></span>(<span class="dt">stress =</span> quikscat<span class="op">$</span>data, <span class="dt">time =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/as.Date">as.Date</a></span>(quikscat<span class="op">$</span>time))</a>
<a class="sourceLine" id="cb43-4" title="4">stressCompare &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cbind">rbind</a></span>(ascatStress,quikscatStress)</a>
<a class="sourceLine" id="cb43-5" title="5">stressCompare<span class="op">$</span>sat &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="st">"ascat"</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(ascatStress)), <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="st">"quikscat"</span>, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/nrow">nrow</a></span>(quikscatStress)))</a>
<a class="sourceLine" id="cb43-6" title="6">stressCompare<span class="op">$</span>sat &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">as.factor</a></span>(stressCompare<span class="op">$</span>sat)</a>
<a class="sourceLine" id="cb43-7" title="7"><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(<span class="dt">data =</span> stressCompare, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(time, stress, <span class="dt">colour =</span> sat)) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_line</a></span>(<span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>()</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/plotstress-1.png" width="576" style="display: block; margin: auto;"></p>
<p>While the two <span style="color:red">wind stress</span> series are close, there is a significant difference in the negative (southward) value on October 28, that is there will be a signifcant difference in the estimated (positive) upwelling value. Combining the series into a longer series would be desirable, but this suggests that there could be problems with inter-year comparisons due to the different sources of the data.</p>
</div>
<div id="lastTimes" class="section level3">
<h3 class="hasAnchor">
<a href="#lastTimes" class="anchor"></a>Taking advantage of “last times”</h3>
<p>The <span style="color:red">ERDDAP</span> server understands a time of “last” as being the last time period available for that dataset, and permits arithmetic using “last”, that is “last-5” is a valid time and will be 5 time periods before the last time (note that since different datasets have different time periods this difference is dataset dependent). For example to extract the last six months of <span style="color:red">SST</span> from <span style="color:red">POES AVHRR</span> we look at the monthly <span style="color:red">agsstmday</span> dataset:</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb44-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb44-2" title="2">xpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">235</span>, <span class="dv">240</span>)</a>
<a class="sourceLine" id="cb44-3" title="3">ypos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">36</span>, <span class="dv">39</span>)</a>
<a class="sourceLine" id="cb44-4" title="4">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"last-5"</span>, <span class="st">"last"</span>)</a>
<a class="sourceLine" id="cb44-5" title="5">poes &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">"agsstamday"</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a></code></pre></div>
<p>Plotting the result using faceting in ggplot2:</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb45-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb45-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(reshape2)</a>
<a class="sourceLine" id="cb45-3" title="3"><span class="co">#&gt; Loading required package: reshape2</span></a>
<a class="sourceLine" id="cb45-4" title="4"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(mapdata)</a>
<a class="sourceLine" id="cb45-5" title="5"></a>
<a class="sourceLine" id="cb45-6" title="6">melt_sst &lt;-<span class="st"> </span><span class="cf">function</span>(longitude,latitude,mTime,sst) {</a>
<a class="sourceLine" id="cb45-7" title="7">  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/dimnames">dimnames</a></span>(sst) &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">long =</span> longitude, <span class="dt">lat =</span> latitude)</a>
<a class="sourceLine" id="cb45-8" title="8">  ret &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/reshape2/topics/melt">melt</a></span>(sst, <span class="dt">value.name =</span> <span class="st">"sst"</span>)</a>
<a class="sourceLine" id="cb45-9" title="9">  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cbind">cbind</a></span>(<span class="dt">date =</span> mTime, ret)</a>
<a class="sourceLine" id="cb45-10" title="10">}</a>
<a class="sourceLine" id="cb45-11" title="11">xpos &lt;-<span class="st"> </span>xpos <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb45-12" title="12">longitude &lt;-<span class="st"> </span>poes<span class="op">$</span>longitude <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb45-13" title="13">latitude &lt;-<span class="st"> </span>poes<span class="op">$</span>latitude</a>
<a class="sourceLine" id="cb45-14" title="14">imon &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">5</span></a>
<a class="sourceLine" id="cb45-15" title="15">tmp &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/lapply">lapply</a></span>(imon, <span class="cf">function</span>(x) <span class="kw">melt_sst</span>(longitude, latitude, poes<span class="op">$</span>time[x], poes<span class="op">$</span>data[,,x]))</a>
<a class="sourceLine" id="cb45-16" title="16">allmons &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/do.call">do.call</a></span>(rbind, tmp)</a>
<a class="sourceLine" id="cb45-17" title="17">allmons<span class="op">$</span>date &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">as.factor</a></span>(allmons<span class="op">$</span>date)</a>
<a class="sourceLine" id="cb45-18" title="18">my.col &lt;-<span class="st"> </span>colors<span class="op">$</span>thermal</a>
<a class="sourceLine" id="cb45-19" title="19">w &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/map_data.html">map_data</a></span>(<span class="st">"worldHires"</span>, <span class="dt">ylim =</span> ypos, <span class="dt">xlim =</span> xpos)</a>
<a class="sourceLine" id="cb45-20" title="20"><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>() <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb45-21" title="21"><span class="st">     </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_raster</a></span>(<span class="dt">data =</span> allmons, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">fill =</span> sst), <span class="dt">interpolate =</span> <span class="ot">TRUE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb45-22" title="22"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon</a></span>(<span class="dt">data =</span> w, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey80"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb45-23" title="23"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradientn</a></span>(<span class="dt">colours =</span> my.col) <span class="op">+</span></a>
<a class="sourceLine" id="cb45-24" title="24"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb45-25" title="25"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span>(<span class="fl">1.3</span>,<span class="dt">xlim =</span> xpos, <span class="dt">ylim =</span> ypos) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb45-26" title="26"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span>(<span class="op">~</span>date, <span class="dt">nrow =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/plotPoes-1.png" width="720" style="display: block; margin: auto;"></p>
</div>
<div id="extracting-multiple-non-consecutive-time-periods" class="section level3">
<h3 class="hasAnchor">
<a href="#extracting-multiple-non-consecutive-time-periods" class="anchor"></a>Extracting Multiple, non-consecutive time periods</h3>
<p>What if we want to extract data from non-consecutive time periods, for example the last six Decembers for an area? <span style="color:blue">SST</span> was unusually warm off of Catalina Island in Dec 2014, and we show this by comparing the same day in December for six years, 2009-2014:</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb46-1" title="1"></a>
<a class="sourceLine" id="cb46-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(reshape2)</a>
<a class="sourceLine" id="cb46-3" title="3"></a>
<a class="sourceLine" id="cb46-4" title="4">allyears &lt;-<span class="st"> </span><span class="ot">NULL</span></a>
<a class="sourceLine" id="cb46-5" title="5">xpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">238</span>, <span class="dv">243</span>)</a>
<a class="sourceLine" id="cb46-6" title="6">ypos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">30</span>, <span class="dv">35</span>)</a>
<a class="sourceLine" id="cb46-7" title="7"><span class="cf">for</span> (year <span class="cf">in</span> <span class="dv">2009</span><span class="op">:</span><span class="dv">2014</span>) {</a>
<a class="sourceLine" id="cb46-8" title="8">  tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/rep">rep</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste</a></span>(year, <span class="st">'-12-20'</span>, <span class="dt">sep =</span> <span class="st">""</span>), <span class="dv">2</span>)</a>
<a class="sourceLine" id="cb46-9" title="9">  tmp &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtracto_3D.html">xtracto_3D</a></span>(<span class="st">'jplMURSST41SST'</span>, xpos, ypos, <span class="dt">tpos =</span> tpos)</a>
<a class="sourceLine" id="cb46-10" title="10"><span class="co">#ggplot is sensitve that the grid is absolutely regular</span></a>
<a class="sourceLine" id="cb46-11" title="11">  tmp<span class="op">$</span>latitude &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/range">range</a></span>(tmp<span class="op">$</span>latitude)[<span class="dv">1</span>], <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/range">range</a></span>(tmp<span class="op">$</span>latitude)[<span class="dv">2</span>], <span class="dt">length.out =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(tmp<span class="op">$</span>latitude))</a>
<a class="sourceLine" id="cb46-12" title="12">  tmp<span class="op">$</span>longitude &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/seq">seq</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/range">range</a></span>(tmp<span class="op">$</span>longitude)[<span class="dv">1</span>], <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/range">range</a></span>(tmp<span class="op">$</span>longitude)[<span class="dv">2</span>], <span class="dt">length.out =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/length">length</a></span>(tmp<span class="op">$</span>longitude))  </a>
<a class="sourceLine" id="cb46-13" title="13">  <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/dimnames">dimnames</a></span>(tmp<span class="op">$</span>data) &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="dt">long =</span> tmp<span class="op">$</span>longitude, <span class="dt">lat =</span> tmp<span class="op">$</span>latitude) </a>
<a class="sourceLine" id="cb46-14" title="14">  ret &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/reshape2/topics/melt">melt</a></span>(tmp<span class="op">$</span>data, <span class="dt">value.name =</span> <span class="st">"sst"</span>)</a>
<a class="sourceLine" id="cb46-15" title="15">  ret &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cbind">cbind</a></span>(<span class="dt">date =</span> tmp<span class="op">$</span>time, ret)</a>
<a class="sourceLine" id="cb46-16" title="16">  allyears &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cbind">rbind</a></span>(allyears, ret)</a>
<a class="sourceLine" id="cb46-17" title="17">}</a>
<a class="sourceLine" id="cb46-18" title="18">allyears<span class="op">$</span>long &lt;-<span class="st"> </span>allyears<span class="op">$</span>long <span class="op">-</span><span class="st"> </span><span class="dv">360</span> </a>
<a class="sourceLine" id="cb46-19" title="19">allyears<span class="op">$</span>date &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/factor">as.factor</a></span>(allyears<span class="op">$</span>date)</a></code></pre></div>
<p>Plotting the result using faceting in ggplot2:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb47-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb47-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(mapdata)</a>
<a class="sourceLine" id="cb47-3" title="3">xpos &lt;-<span class="st"> </span>xpos <span class="op">-</span><span class="st"> </span><span class="dv">360</span></a>
<a class="sourceLine" id="cb47-4" title="4"><span class="co">#long&lt;-allyears$longitude-360</span></a>
<a class="sourceLine" id="cb47-5" title="5"><span class="co">#lat&lt;-allyears$latitude</span></a>
<a class="sourceLine" id="cb47-6" title="6">coast &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/map_data.html">map_data</a></span>(<span class="st">"worldHires"</span>, <span class="dt">ylim =</span> ypos, <span class="dt">xlim =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="fl">123.5</span>, <span class="fl">-120.</span>))</a>
<a class="sourceLine" id="cb47-7" title="7">my.col &lt;-<span class="st"> </span>colors<span class="op">$</span>thermal</a>
<a class="sourceLine" id="cb47-8" title="8"></a>
<a class="sourceLine" id="cb47-9" title="9"><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(<span class="dt">data =</span> allyears, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">fill =</span> sst)) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb47-10" title="10"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon</a></span>(<span class="dt">data =</span> coast, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey80"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb47-11" title="11"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_raster</a></span>(<span class="dt">interpolate =</span> <span class="ot">TRUE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb47-12" title="12"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradientn</a></span>(<span class="dt">colours =</span> my.col) <span class="op">+</span></a>
<a class="sourceLine" id="cb47-13" title="13"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span></a>
<a class="sourceLine" id="cb47-14" title="14"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span>(<span class="fl">1.3</span>, <span class="dt">xlim =</span> xpos, <span class="dt">ylim =</span> ypos) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb47-15" title="15"><span class="st">  </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span>(<span class="op">~</span>date, <span class="dt">nrow =</span> <span class="dv">2</span>)</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/plotCatalina-1.png" width="720" style="display: block; margin: auto;"></p>
<p>This example uses the <span style="color:red">MUR (Multi-scale Ultra-high Resolution)</span> <span style="color:red">SST</span>, a high quality ultra-high resolution <span style="color:red">SST</span> produced by the <span style="color:red">MISST</span> project.</p>
</div>
</div>
<div id="using-xtractogon" class="section level2">
<h2 class="hasAnchor">
<a href="#using-xtractogon" class="anchor"></a>Using <code>xtractogon</code>
</h2>
<p>The <code>xtractogon</code> function extracts a time-series of satellite data that are within a user supplied polygon. As an example, the boundary points of the Monterey Bay National Marine Sanctuary are available in the <code>mbnms</code> dataset which are loaded with the <code>xtractomatic</code> package. The <code>mbnms</code> dataset containes two variables, <span style="color:blue">Latitude</span> and <span style="color:blue">Longitude</span>, which define the boundaries of the sanctuary:</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb48-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb48-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(mbnms)</a>
<a class="sourceLine" id="cb48-3" title="3"><span class="co">#&gt; 'data.frame':    6666 obs. of  2 variables:</span></a>
<a class="sourceLine" id="cb48-4" title="4"><span class="co">#&gt;  $ Longitude: num  -123 -123 -123 -123 -123 ...</span></a>
<a class="sourceLine" id="cb48-5" title="5"><span class="co">#&gt;  $ Latitude : num  37.9 37.9 37.9 37.9 37.9 ...</span></a></code></pre></div>
<p>The example below extracts a time-series of monthly <span style="color:red">VIIRS</span> chlorophyll data within the MBNMS.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb49-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb49-2" title="2">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"2014-09-01"</span>, <span class="st">"2014-10-01"</span>)</a>
<a class="sourceLine" id="cb49-3" title="3">xpos &lt;-<span class="st"> </span>mbnms<span class="op">$</span>Longitude</a>
<a class="sourceLine" id="cb49-4" title="4">ypos &lt;-<span class="st"> </span>mbnms<span class="op">$</span>Latitude</a>
<a class="sourceLine" id="cb49-5" title="5">sanctchl &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtractogon.html">xtractogon</a></span>(<span class="st">'erdVH3chlamday'</span>, xpos, ypos, <span class="dt">tpos =</span> tpos )</a>
<a class="sourceLine" id="cb49-6" title="6"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(sanctchl)</a></code></pre></div>
<pre><code>#&gt; List of 7
#&gt;  $ data       : num [1:50, 1:57, 1:2] NA NA NA NA NA NA NA NA NA NA ...
#&gt;  $ varname    : chr "chla"
#&gt;  $ datasetname: chr "erdVH3chlamday"
#&gt;  $ latitude   : num [1:57(1d)] 35.6 35.6 35.6 35.7 35.7 ...
#&gt;  $ longitude  : num [1:50(1d)] -123 -123 -123 -123 -123 ...
#&gt;  $ time       : POSIXlt[1:2], format: "2014-09-15" "2014-10-15"
#&gt;  $ altitude   : logi NA</code></pre>
<p>The extract (see<code><a href="https://www.rdocumentation.org/packages/utils/topics/str">str(sanctchl)</a></code>) contains two time periods of <span style="color:red">chlorophyll</span> masked for data only in the sanctuary boundaries.</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb51-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb51-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(mapdata)</a>
<a class="sourceLine" id="cb51-3" title="3">xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="fl">123.5</span>, <span class="fl">-121.</span>)</a>
<a class="sourceLine" id="cb51-4" title="4">ylim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">35</span>, <span class="dv">38</span>)</a>
<a class="sourceLine" id="cb51-5" title="5">mbnmsFrame &lt;-<span class="st"> </span><span class="kw">mapFrame</span>(sanctchl<span class="op">$</span>longitude <span class="op">+</span><span class="st"> </span><span class="dv">360</span>, sanctchl<span class="op">$</span>latitude, <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/Log">log</a></span>(sanctchl<span class="op">$</span>data[, , <span class="dv">2</span>]))</a>
<a class="sourceLine" id="cb51-6" title="6">my.col &lt;-<span class="st"> </span>colors<span class="op">$</span>algae</a>
<a class="sourceLine" id="cb51-7" title="7">w &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/map_data.html">map_data</a></span>(<span class="st">"worldHires"</span>, <span class="dt">ylim =</span> ylim, <span class="dt">xlim =</span> xlim)</a>
<a class="sourceLine" id="cb51-8" title="8">myplot &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span>(<span class="dt">data =</span> mbnms, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> Longitude, <span class="dt">y =</span> Latitude), <span class="dt">colour =</span> <span class="st">"black"</span>)   </a>
<a class="sourceLine" id="cb51-9" title="9">myplot &lt;-<span class="st"> </span>myplot <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb51-10" title="10"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_raster</a></span>(<span class="dt">data =</span> mbnmsFrame, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y, <span class="dt">fill =</span> chla), <span class="dt">interpolate =</span> <span class="ot">FALSE</span>) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb51-11" title="11"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon</a></span>(<span class="dt">data =</span> w, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey80"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb51-12" title="12"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradientn</a></span>(<span class="dt">colours =</span> my.col, <span class="dt">limits =</span> <span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="dv">2</span>, <span class="fl">4.5</span>)) <span class="op">+</span></a>
<a class="sourceLine" id="cb51-13" title="13"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span>(<span class="st">"latitude"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span>(<span class="st">"longitude"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb51-14" title="14"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span>(<span class="fl">1.3</span>, <span class="dt">xlim =</span> xlim, <span class="dt">ylim =</span> ylim) <span class="op">+</span><span class="st"> </span></a>
<a class="sourceLine" id="cb51-15" title="15"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste</a></span>(<span class="st">"log(Chla) in MBNMS"</span>, sanctchl<span class="op">$</span>time[<span class="dv">2</span>]))</a>
<a class="sourceLine" id="cb51-16" title="16">myplot</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/mbnmsChlaPlot-1.png" width="480" style="display: block; margin: auto;"></p>
<p>The MBNMS is famous for containing the Monterey Canyon, which reaches depths of up to 3,600 m (11,800 ft) below surface level at its deepest. <code>xtractogon</code> can extract the bathymetry data for the MBNMS from the <span style="color:red">ETOPO</span> dataset:</p>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb52-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(xtractomatic)</a>
<a class="sourceLine" id="cb52-2" title="2">tpos &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="st">"2014-09-01"</span>, <span class="st">"2014-10-01"</span>)</a>
<a class="sourceLine" id="cb52-3" title="3"><span class="co">#tpos &lt;-as.Date(tpos)</span></a>
<a class="sourceLine" id="cb52-4" title="4">xpos &lt;-<span class="st"> </span>mbnms<span class="op">$</span>Longitude</a>
<a class="sourceLine" id="cb52-5" title="5">ypos &lt;-<span class="st"> </span>mbnms<span class="op">$</span>Latitude</a>
<a class="sourceLine" id="cb52-6" title="6">bathy &lt;-<span class="st"> </span><span class="kw"><a href="../reference/xtractogon.html">xtractogon</a></span>(<span class="st">'ETOPO180'</span>, xpos, ypos)</a>
<a class="sourceLine" id="cb52-7" title="7"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(bathy)</a></code></pre></div>
<pre><code>#&gt; List of 7
#&gt;  $ data       : num [1:123, 1:141, 1] NA NA NA NA NA NA NA NA NA NA ...
#&gt;  $ varname    : chr "altitude"
#&gt;  $ datasetname: chr "etopo180"
#&gt;  $ latitude   : num [1:141(1d)] 35.5 35.6 35.6 35.6 35.6 ...
#&gt;  $ longitude  : num [1:123(1d)] -123 -123 -123 -123 -123 ...
#&gt;  $ time       : logi NA
#&gt;  $ altitude   : logi NA</code></pre>
<p>Mapping the data to show the canyon:</p>
<div class="sourceCode" id="cb54"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb54-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(ggplot2)</a>
<a class="sourceLine" id="cb54-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(mapdata)</a>
<a class="sourceLine" id="cb54-3" title="3">xlim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="op">-</span><span class="fl">123.5</span>, <span class="fl">-121.</span>)</a>
<a class="sourceLine" id="cb54-4" title="4">ylim &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/c">c</a></span>(<span class="dv">35</span>, <span class="dv">38</span>)</a>
<a class="sourceLine" id="cb54-5" title="5">mbnmsFrame &lt;-<span class="st"> </span><span class="kw">mapFrame</span>(bathy<span class="op">$</span>longitude <span class="op">+</span><span class="st"> </span><span class="dv">360</span>, bathy<span class="op">$</span>latitude, bathy<span class="op">$</span>data[, , <span class="dv">1</span>])</a>
<a class="sourceLine" id="cb54-6" title="6">w &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/map_data.html">map_data</a></span>(<span class="st">"worldHires"</span>, <span class="dt">ylim =</span> ylim, <span class="dt">xlim =</span> xlim)</a>
<a class="sourceLine" id="cb54-7" title="7">myplot &lt;-<span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_path.html">geom_path</a></span>(<span class="dt">data =</span> mbnms,<span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> Longitude, <span class="dt">y =</span> Latitude), <span class="dt">colour =</span> <span class="st">"black"</span>)   </a>
<a class="sourceLine" id="cb54-8" title="8">myplot &lt;-<span class="st"> </span>myplot <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_tile.html">geom_raster</a></span>(<span class="dt">data =</span> mbnmsFrame, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> x, <span class="dt">y =</span> y, <span class="dt">fill =</span> chla),<span class="dt">interpolate =</span> <span class="ot">FALSE</span>, <span class="dt">na.rm =</span> <span class="ot">TRUE</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb54-9" title="9"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/geom_polygon.html">geom_polygon</a></span>(<span class="dt">data =</span> w, <span class="kw"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="dt">x =</span> long, <span class="dt">y =</span> lat, <span class="dt">group =</span> group), <span class="dt">fill =</span> <span class="st">"grey80"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb54-10" title="10"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/ggtheme.html">theme_bw</a></span>() <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/scale_gradient.html">scale_fill_gradient</a></span>(<span class="dt">na.value =</span> <span class="ot">NA</span>, <span class="dt">name =</span> <span class="st">"Depth"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb54-11" title="11"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ylab</a></span>(<span class="st">"latitude"</span>) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">xlab</a></span>(<span class="st">"longitude"</span>) <span class="op">+</span></a>
<a class="sourceLine" id="cb54-12" title="12"><span class="st">    </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/coord_fixed.html">coord_fixed</a></span>(<span class="fl">1.3</span>, <span class="dt">xlim =</span> xlim, <span class="dt">ylim =</span> ylim) <span class="op">+</span><span class="st"> </span><span class="kw"><a href="https://ggplot2.tidyverse.org/reference/labs.html">ggtitle</a></span>(<span class="st">"MBNMS Bathymetry"</span>)</a>
<a class="sourceLine" id="cb54-13" title="13">myplot</a></code></pre></div>
<p><img src="Usingxtractomatic_files/figure-html/mbnmsBathyPlot-1.png" width="480" style="display: block; margin: auto;"></p>
</div>
<div id="what-happens-when-you-request-an-extract" class="section level2">
<h2 class="hasAnchor">
<a href="#what-happens-when-you-request-an-extract" class="anchor"></a>What happens when you request an extract</h2>
<p>When you make an <code>xtractomatic</code> request, particularly for track data using the <code>xtracto</code> function, it is important to understand what is extracted, because the remote dataset requested likely will have a different temporal and spatial resolution then the local dataset.</p>
<p>Specifically, let <code>longitude</code>, <code>latitude</code> and <code>time</code> be the coordinate system of the remote <span style="color:red">ERDDAP</span> dataset, and let <code>xpos</code>, <code>ypos</code> and <code>tpos</code> be the bounds of a request. Then the <span style="color:red">ERDDAP</span> request is based on the nearest grid point of the <span style="color:red">ERDDAP</span> dataset:</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb55-1" title="1">latitude[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(latitude <span class="op">-</span><span class="st"> </span>ypos[<span class="dv">1</span>]))]  <span class="co"># minimum latitude</span></a>
<a class="sourceLine" id="cb55-2" title="2">latitude[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(latitude <span class="op">-</span><span class="st"> </span>ypos[<span class="dv">2</span>]))]  <span class="co"># maximum latitude</span></a>
<a class="sourceLine" id="cb55-3" title="3">longitude[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(longitude<span class="op">-</span><span class="st"> </span>xpos[<span class="dv">1</span>]))] <span class="co"># minimum longitude</span></a>
<a class="sourceLine" id="cb55-4" title="4">longitude[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(longitude <span class="op">-</span><span class="st"> </span>xpos[<span class="dv">2</span>]))] <span class="co"># maximum longitude</span></a>
<a class="sourceLine" id="cb55-5" title="5">isotime[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(time<span class="op">-</span><span class="st"> </span>tpos[<span class="dv">1</span>]))] <span class="co"># minimum time</span></a>
<a class="sourceLine" id="cb55-6" title="6">isotime[<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/which.min">which.min</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/MathFun">abs</a></span>(time <span class="op">-</span><span class="st"> </span>tpos[<span class="dv">2</span>]))] <span class="co"># maximum time</span></a></code></pre></div>
<p>where <code>tpos</code> and <code>time</code> have been converted to an <span style="color:red">R</span> date format so that it is a number rather than a string. For example, the FNMOC 6-hourly Ekman transports are on a 1-degree grid. A request for the data at a longitude of 220.2 and a latitude of 38.7 will return the result at a longtiude of 220 and a latitude of 39.</p>
</div>
<div id="dataset" class="section level2">
<h2 class="hasAnchor">
<a href="#dataset" class="anchor"></a>Selecting a dataset</h2>
<p>As seen in the examples above, the functions <code>xtractomatic</code>, <code>xtracto</code>, <code>xtracto_3D</code>, and <code>xtractogon</code> all use the parameter <span style="color:red">dtype</span> to specify the combination of dataset and parameter to use. The datasets accessed by <code>xtractomatic</code> are a subset of the almost 900 datasets available on ERD’s ERDDAP server at <a href="http://coastwatch.pfeg.noaa.gov/erddap/index.html" class="uri">http://coastwatch.pfeg.noaa.gov/erddap/index.html</a>. The datasets chosen to be accessible by <code>xtractomatic</code> are those that are the most useful to the majority of our users. This version of <code>xtractomatic</code> accesses 165 datasets. Information about a particular dataset is availble via the <code>getInfo</code> function. <code>getInfo</code> takes either the numbered value of a dataset, or the datatype name (the parameter <span style="color:red">dtypename</span>), which is the first information returned by <code>getInfo</code>. <code>getInfo</code> does not return the number of the dataset, the use of the <span style="color:red">dtypename</span> is encouraged rather than the number associated with the dataset. It is strongly recommended that <span style="color:blue">dtype</span> not be passed as a number, as the numbers can change and will not be used in the next version.</p>
<p>There are a large number of temporally composited datasets available. The temporal composite time interval is usually indicated in the <span style="color:red">dtypename</span> (for example “phssta8day” is an 8-day composite), <span style="color:red">datasetname</span> (for example “erdPHssta8day”) and <span style="color:red">longname</span> (for example “SST, Pathfinder Ver 5.0, Day and Night, Global, Science Quality (8 Day Composite)”) variables associated with a dataset. The time interval between data points in the time-series is indicated by the <span style="color:red">timespacing</span> parameter. For example note the difference in timespacing for <span style="color:red">dtypename</span>=“mhchla8day” and <span style="color:red">dtypename</span>=“mbchla8day”, which are both 8-day composites.</p>
<div class="sourceCode" id="cb56"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb56-1" title="1"><span class="kw"><a href="../reference/getInfo.html">getInfo</a></span>(<span class="st">'mhchla8day'</span>) </a>
<a class="sourceLine" id="cb56-2" title="2"><span class="co">#&gt; List of 19</span></a>
<a class="sourceLine" id="cb56-3" title="3"><span class="co">#&gt;  $ dtypename       : chr "mhchla8day"</span></a>
<a class="sourceLine" id="cb56-4" title="4"><span class="co">#&gt;  $ datasetname     : chr "erdMH1chla8day"</span></a>
<a class="sourceLine" id="cb56-5" title="5"><span class="co">#&gt;  $ longname        : chr "Chlorophyll-a, Aqua MODIS, NPP, L3SMI, Global, Science Quality (8 Day Composite)"</span></a>
<a class="sourceLine" id="cb56-6" title="6"><span class="co">#&gt;  $ varname         : chr "chlorophyll"</span></a>
<a class="sourceLine" id="cb56-7" title="7"><span class="co">#&gt;  $ hasAlt          : logi FALSE</span></a>
<a class="sourceLine" id="cb56-8" title="8"><span class="co">#&gt;  $ latSouth        : logi FALSE</span></a>
<a class="sourceLine" id="cb56-9" title="9"><span class="co">#&gt;  $ lon360          : logi FALSE</span></a>
<a class="sourceLine" id="cb56-10" title="10"><span class="co">#&gt;  $ minLongitude    : num -180</span></a>
<a class="sourceLine" id="cb56-11" title="11"><span class="co">#&gt;  $ maxLongitude    : num 180</span></a>
<a class="sourceLine" id="cb56-12" title="12"><span class="co">#&gt;  $ longitudeSpacing: num 0.0417</span></a>
<a class="sourceLine" id="cb56-13" title="13"><span class="co">#&gt;  $ minLatitude     : num -90</span></a>
<a class="sourceLine" id="cb56-14" title="14"><span class="co">#&gt;  $ maxLatitude     : num 90</span></a>
<a class="sourceLine" id="cb56-15" title="15"><span class="co">#&gt;  $ latitudeSpacing : num -0.0417</span></a>
<a class="sourceLine" id="cb56-16" title="16"><span class="co">#&gt;  $ minAltitude     : num NA</span></a>
<a class="sourceLine" id="cb56-17" title="17"><span class="co">#&gt;  $ maxAltitude     : num NA</span></a>
<a class="sourceLine" id="cb56-18" title="18"><span class="co">#&gt;  $ minTime         : chr "2003-01-05"</span></a>
<a class="sourceLine" id="cb56-19" title="19"><span class="co">#&gt;  $ maxTime         : chr "2019-02-14"</span></a>
<a class="sourceLine" id="cb56-20" title="20"><span class="co">#&gt;  $ timeSpacing     : num NA</span></a>
<a class="sourceLine" id="cb56-21" title="21"><span class="co">#&gt;  $ infoURL         : chr "http://oceancolor.gsfc.nasa.gov/"</span></a>
<a class="sourceLine" id="cb56-22" title="22"><span class="kw"><a href="../reference/getInfo.html">getInfo</a></span>(<span class="st">'mbchla8day'</span>) </a>
<a class="sourceLine" id="cb56-23" title="23"><span class="co">#&gt; List of 19</span></a>
<a class="sourceLine" id="cb56-24" title="24"><span class="co">#&gt;  $ dtypename       : chr "mbchla8day"</span></a>
<a class="sourceLine" id="cb56-25" title="25"><span class="co">#&gt;  $ datasetname     : chr "erdMBchla8day"</span></a>
<a class="sourceLine" id="cb56-26" title="26"><span class="co">#&gt;  $ longname        : chr "Chlorophyll-a, Aqua MODIS, NPP, Pacific Ocean (8 Day Composite)"</span></a>
<a class="sourceLine" id="cb56-27" title="27"><span class="co">#&gt;  $ varname         : chr "chlorophyll"</span></a>
<a class="sourceLine" id="cb56-28" title="28"><span class="co">#&gt;  $ hasAlt          : logi TRUE</span></a>
<a class="sourceLine" id="cb56-29" title="29"><span class="co">#&gt;  $ latSouth        : logi TRUE</span></a>
<a class="sourceLine" id="cb56-30" title="30"><span class="co">#&gt;  $ lon360          : logi TRUE</span></a>
<a class="sourceLine" id="cb56-31" title="31"><span class="co">#&gt;  $ minLongitude    : num 120</span></a>
<a class="sourceLine" id="cb56-32" title="32"><span class="co">#&gt;  $ maxLongitude    : num 320</span></a>
<a class="sourceLine" id="cb56-33" title="33"><span class="co">#&gt;  $ longitudeSpacing: num 0.025</span></a>
<a class="sourceLine" id="cb56-34" title="34"><span class="co">#&gt;  $ minLatitude     : num -45</span></a>
<a class="sourceLine" id="cb56-35" title="35"><span class="co">#&gt;  $ maxLatitude     : num 65</span></a>
<a class="sourceLine" id="cb56-36" title="36"><span class="co">#&gt;  $ latitudeSpacing : num 0.025</span></a>
<a class="sourceLine" id="cb56-37" title="37"><span class="co">#&gt;  $ minAltitude     : num 0</span></a>
<a class="sourceLine" id="cb56-38" title="38"><span class="co">#&gt;  $ maxAltitude     : num 0</span></a>
<a class="sourceLine" id="cb56-39" title="39"><span class="co">#&gt;  $ minTime         : chr "2005-12-29"</span></a>
<a class="sourceLine" id="cb56-40" title="40"><span class="co">#&gt;  $ maxTime         : chr "2019-03-10"</span></a>
<a class="sourceLine" id="cb56-41" title="41"><span class="co">#&gt;  $ timeSpacing     : num NA</span></a>
<a class="sourceLine" id="cb56-42" title="42"><span class="co">#&gt;  $ infoURL         : chr "http://coastwatch.pfeg.noaa.gov/infog/MB_chla_las.html"</span></a></code></pre></div>
<p>The difference is that the latter dataset (<code>mbchla8day</code>) is a running 8-day composite, so there is a value for every day, while the former dataset (<code>mhchla8day</code>) calculates composites for non-overlapping 8-day periods.</p>
<p>The <code>searchData</code> function can be used to search for a subset of that satisfy certain criteria (note that the <code>searchData</code> has changed since the previous version). <code>searchData</code> requires a list of of entries of the form “searchType:searchString”, where each element of “the first item of”searchType"" has to be one of <code>dtypename, datasetname, longname, varname</code>, and “searchString” is the string to search for in that field. For example to find all of the datasets that have a <code>varname</code> that contains <code>chl</code> and a <code>datasetname</code> that contains <code>mday</code> (most monthly datasets have <code>mday</code> in their name):</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb57-1" title="1">mylist &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="st">'varname:chl'</span>, <span class="st">'datasetname:mday'</span>)</a>
<a class="sourceLine" id="cb57-2" title="2">searchResult &lt;-<span class="st"> </span><span class="kw"><a href="../reference/searchData.html">searchData</a></span>(mylist)</a></code></pre></div>
<p>which returns among others the three <span style="color:red">chlorophyll</span> datasets extracted in the <code>xtracto_3D</code> section. The search result can be easily perused by using <code><a href="https://www.rdocumentation.org/packages/utils/topics/View">View()</a></code> or by:</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb58-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">require</a></span>(<span class="st">"DT"</span>)</a>
<a class="sourceLine" id="cb58-2" title="2"><span class="co">#&gt; Loading required package: DT</span></a>
<a class="sourceLine" id="cb58-3" title="3">DT<span class="op">::</span><span class="kw"><a href="https://www.rdocumentation.org/packages/DT/topics/datatable">datatable</a></span>(searchResult)</a></code></pre></div>
<div id="htmlwidget-1458adf26eeff50d5d2c" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-1458adf26eeff50d5d2c">{"x":{"filter":"none","data":[["dtypename","datasetname","longname","varname","hasAlt","latSouth","lon360","minLongitude","maxLongitude","longitudeSpacing","minLatitude","maxLatitude","latitudeSpacing","minAltitude","maxAltitude","minTime","maxTime","timeSpacing","infoURL"],["erdSAchlamday","erdSAchlamday","Chlorophyll-a, Orbview-2 SeaWiFS, West US, Science Quality (Monthly Composite) DEPRECATED","chlorophyll",true,true,true,225.012,255,0.036,20,54.992,0.036,0,0,"1997-09-16","2006-10-16",null,"http://coastwatch.pfeg.noaa.gov/infog/SW_chla_las.html"],["erdSW1chlamday","erdSW1chlamday","Chlorophyll-a, Orbview-2 SeaWiFS, R2014.0, 0.1°, Global (Monthly Composite)","chlorophyll",false,false,false,-179.9583,179.9584,0.08333334,-89.95834,89.95834,0.08333334,null,null,"1997-09-16","2010-12-16",1,"http://oceandata.sci.gsfc.nasa.gov"],["erdVH3chlamday","erdVH3chlamday","VIIRSN, Suomi-NPP, Level-3 SMI, NASA, Global, 4km, Chlorophyll a, OCI Algorithm, 2012-present, Monthly","chla",false,false,false,-179.9792,179.9792,0.04166667,-89.97917,89.97917,-0.04166667,null,null,"2012-01-15","2017-10-15",null,"http://oceancolor.gsfc.nasa.gov/"],["erdVHNchlamday","erdVHNchlamday","Chlorophyll a, North Pacific, NOAA VIIRS, 750m resolution (Monthly Composite)","chla",true,false,false,-180.03375,-110.00625,0.0075,-0.10875,89.77125,0.0075,0,0,"2015-02-25","2018-12-16",null,null],["mhchlamday","erdMH1chlamday","Chlorophyll-a, Aqua MODIS, NPP, L3SMI, Global, Science Quality (Monthly Composite)","chlorophyll",false,false,false,-179.9792,179.9792,0.04166667,-89.97916,89.97918,-0.04166667,null,null,"2003-01-16","2019-01-16",null,"http://oceancolor.gsfc.nasa.gov/"],["swchlamday","erdSWchlamday","Chlorophyll-a, Orbview-2 SeaWiFS, Global (Monthly Composite) DEPRECATED","chlorophyll",true,true,true,0,360,0.08335263,-90,90,0.08337193,0,0,"1997-09-16","2010-12-16",null,"http://coastwatch.pfeg.noaa.gov/infog/SW_chla_las.html"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>erdSAchlamday<\/th>\n      <th>erdSW1chlamday<\/th>\n      <th>erdVH3chlamday<\/th>\n      <th>erdVHNchlamday<\/th>\n      <th>mhchlamday<\/th>\n      <th>swchlamday<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"order":[],"autoWidth":false,"orderClasses":false,"columnDefs":[{"orderable":false,"targets":0}]}},"evals":[],"jsHooks":[]}</script><p>If only doing the first search the code would be:</p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb59-1" title="1">mylist &lt;-<span class="st"> </span><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/list">list</a></span>(<span class="st">'varname:chl'</span>)</a>
<a class="sourceLine" id="cb59-2" title="2">searchResult &lt;-<span class="st"> </span><span class="kw"><a href="../reference/searchData.html">searchData</a></span>(mylist)</a></code></pre></div>
<p><code>searchData</code> iteratively refines the matches in the order given by the list, thus it can be viewed as doing a logical “AND” on the matches.</p>
<p>The <span style="color:red">longname</span> of a dataset often contains a lot of this information. Alternatively you can generate a list of the <span style="color:red">datasetname</span> and <span style="color:red">longname</span> of all of the datasets accessed by <code>xtractomatic</code> (we only show the first five lines of output):</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb60-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/cat">cat</a></span>(<span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/paste">paste0</a></span>(xtractomatic<span class="op">:::</span>erddapStruct[<span class="st">"datasetname"</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>],<span class="st">': '</span> , xtractomatic<span class="op">:::</span>erddapStruct[<span class="st">"longname"</span>, <span class="dv">1</span><span class="op">:</span><span class="dv">5</span>],<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>))</a>
<a class="sourceLine" id="cb60-2" title="2"><span class="co">#&gt; list(datasetname = "erdAGssta14day"): list(longname = "sst")</span></a>
<a class="sourceLine" id="cb60-3" title="3"><span class="co">#&gt;  list(datasetname = "erdAGssta1day"): list(longname = "SST, POES AVHRR, LAC, West US, Day and Night (14 Day Composite)")</span></a>
<a class="sourceLine" id="cb60-4" title="4"><span class="co">#&gt;  list(datasetname = "erdAGssta3day"): list(longname = "SST, POES AVHRR, GAC, Global, Day and Night (3 Day Composite)")</span></a>
<a class="sourceLine" id="cb60-5" title="5"><span class="co">#&gt;  list(datasetname = "erdAGssta8day"): list(longname = "SST, POES AVHRR, GAC, Global, Day and Night (8 Day Composite)")</span></a>
<a class="sourceLine" id="cb60-6" title="6"><span class="co">#&gt;  list(datasetname = "erdAGsstamday"): list(longname = "SST, POES AVHRR, GAC, Global, Day and Night (Monthly Composite)")</span></a></code></pre></div>
<p>and then use <code>getInfo</code> with the <span style="color:red">datasetname</span> to see all of the information on that dataset</p>
<div id="topographic-datasets" class="section level3">
<h3 class="hasAnchor">
<a href="#topographic-datasets" class="anchor"></a>Topographic datasets</h3>
<p><code>xtractomatic</code> can extract data from two topographic datasets (<span style="color:red">ETOPO</span>) , with <span style="color:blue">dtypename</span> of “ETOPO180” and “ETOPO360”, which have longitudes ranging from -180 to 180 and 0 to 360 respectively. Currently the <code>getInfo</code> and <code>searchData</code> commands do not work with these two datasets, but <code>xtracto</code>, <code>xtracto_3D</code>, and <code>xtractogon</code> do.</p>
</div>
</div>
<div id="new" class="section level2">
<h2 class="hasAnchor">
<a href="#new" class="anchor"></a>What has Changed and Steps Going Forward</h2>
<p>The <a href="#refactor">earlier section</a> covers the changes to the arguments to the functions. The examples should make clear how the function calls now work.</p>
<p>The function <code><a href="../reference/searchData.html">searchData()</a></code> no longer uses a list of list, instead it uses a simple list where the each “searchType” and “searchString” are set off by a colon as in “searchType:searchString”.</p>
<p>In this and all past version of <code>xtractomatic</code>, information about the datasets was built into the functions. In the present case the dataset information is stored in a dataframe called <code>erddapStruct</code> which is auotmatically loaded when you loaded the package.</p>
<p>This has the disadvantage that it is tied to specific datasets and a specifc <span style="color:red">ERDDAP</span> server, rather than working with any dataset served by any <span style="color:red">ERDDAP</span>.</p>
<p>The dataset was specified by the <code>dtype</code>, which could be either a number or a character string, and references the information in that dataframe. The <code>dtype</code> names in this version for the most part are same, <strong>BUT <code>dtype</code> AS NUMBERS ARE NO LONGER SUPPORTED</strong>. If you have used <code>xtractomatic</code> before you need to check that the <code>dtype</code> information that you are passing is what you think it is. You can do this using the supplied <code><a href="../reference/getInfo.html">getInfo()</a></code> or <code><a href="../reference/searchData.html">searchData()</a></code> functions or peruse the <code>erddapStruct</code> dataframe. There are many more datasets available in this version, and now “last” can be used as time to get the last time period available for that dataset.</p>
<p>Every <span style="color:red">ERDDAP</span> dataset has an <span style="color:red">ERDDAP</span> “dataset ID”, as well one or more variables associated with that “dataset ID”. Some datasets, such as the <span style="color:red">ASCAT winds</span> have multiple variables associated with the dataset:</p>
<p><a href="https://coastwatch.pfeg.noaa.gov/erddap/griddap/erdQAstress1day.html" class="uri">https://coastwatch.pfeg.noaa.gov/erddap/griddap/erdQAstress1day.html</a>.</p>
<p>This information is contained in <code>erddapStruct$datasetname</code> and <code>erddapStruct$varname</code>. Since a single dataset may have more than one variable, <code>dtype</code> as character string is a way to have a unique dataset id and variable name in a single variable. A more general version of <code>xtractomatic</code>, called <code>rerddapXtracto</code>, is under development. <code>rerddapXtracto</code> will work with any gridded dataset on any <span style="color:red">ERDDAP</span> by using the <span style="color:red">ROpenSci</span> package <code>rerddap</code>. Information on <code>rerddapXtracto</code> can be found at:</p>
<p><a href="https://github.com/rmendels/rerddapXtracto" class="uri">https://github.com/rmendels/rerddapXtracto</a></p>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#introduction">Introduction</a></li>
      <li><a href="#setting-up">Setting up</a></li>
      <li><a href="#getting-started">Getting Started</a></li>
      <li><a href="#reading-in-tagged-data">Reading in tagged data</a></li>
      <li><a href="#using-xtracto_3d">Using <code>xtracto_3D</code></a></li>
      <li><a href="#using-xtractogon">Using <code>xtractogon</code></a></li>
      <li><a href="#what-happens-when-you-request-an-extract">What happens when you request an extract</a></li>
      <li><a href="#dataset">Selecting a dataset</a></li>
      <li><a href="#new">What has Changed and Steps Going Forward</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by Roy Mendelssohn.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.9000.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
